export const $APP = {};
export const shadow$provide = {};
export const $jscomp = {};
var f,t=function(a){var b=typeof a;return"object"!=b?b:a?Array.isArray(a)?"array":b:"null"},aa=function(a){const b=[];let c=0;for(const d in a)b[c++]=d;return b},ba=function(a,b){null!=a&&this.append.apply(this,arguments)},u=function(a){return null!=a&&!1!==a},da=function(a){return a instanceof Array},v=function(a,b){return a[t(null==b?null:b)]?!0:a._?!0:!1},x=function(a,b){var c=null==b?null:b.constructor;return Error(["No protocol method ",a," defined for type ",u(u(c)?c.Kb:c)?c.pb:t(b),": ",b].join(""))},
ea=function(a){var b=a.pb;return u(b)?b:y.g(a)},z=function(a){for(var b=a.length,c=Array(b),d=0;;)if(d<b)c[d]=a[d],d+=1;else break;return c},fa=function(){},ha=function(a){if(null!=a&&null!=a.U)a=a.U(a);else{var b=ha[t(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=ha._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw x("ICounted.-count",a);}return a},ia=function(){},ja=function(a){if(null!=a&&null!=a.V)a=a.V(a);else{var b=ja[t(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,
a);else if(b=ja._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw x("IEmptyableCollection.-empty",a);}return a},ka=function(a,b){if(null!=a&&null!=a.T)a=a.T(a,b);else{var c=ka[t(null==a?null:a)];if(null!=c)a=c.h?c.h(a,b):c.call(null,a,b);else if(c=ka._,null!=c)a=c.h?c.h(a,b):c.call(null,a,b);else throw x("ICollection.-conj",a);}return a},la=function(){},C=function(a){if(null!=a&&null!=a.aa)a=a.aa(a);else{var b=C[t(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=C._,null!=b)a=b.g?
b.g(a):b.call(null,a);else throw x("ISeq.-first",a);}return a},D=function(a){if(null!=a&&null!=a.fa)a=a.fa(a);else{var b=D[t(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=D._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw x("ISeq.-rest",a);}return a},ma=function(){},na=function(){},oa=function(){},pa=function(a,b){if(null!=a&&null!=a.Ua)a=a.Ua(a,b);else{var c=pa[t(null==a?null:a)];if(null!=c)a=c.h?c.h(a,b):c.call(null,a,b);else if(c=pa._,null!=c)a=c.h?c.h(a,b):c.call(null,a,b);
else throw x("IAssociative.-contains-key?",a);}return a},qa=function(a,b,c){if(null!=a&&null!=a.xa)a=a.xa(a,b,c);else{var d=qa[t(null==a?null:a)];if(null!=d)a=d.m?d.m(a,b,c):d.call(null,a,b,c);else if(d=qa._,null!=d)a=d.m?d.m(a,b,c):d.call(null,a,b,c);else throw x("IAssociative.-assoc",a);}return a},ra=function(){},sa=function(a){if(null!=a&&null!=a.Eb)a=a.key;else{var b=sa[t(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=sa._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw x("IMapEntry.-key",
a);}return a},ua=function(a){if(null!=a&&null!=a.Fb)a=a.G;else{var b=ua[t(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=ua._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw x("IMapEntry.-val",a);}return a},va=function(){},wa=function(a){if(null!=a&&null!=a.Ab)a=a.G;else{var b=wa[t(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=wa._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw x("IDeref.-deref",a);}return a},xa=function(){},ya=function(a){if(null!=a&&null!=a.O)a=
a.O(a);else{var b=ya[t(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=ya._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw x("IMeta.-meta",a);}return a},za=function(a,b){if(null!=a&&null!=a.P)a=a.P(a,b);else{var c=za[t(null==a?null:a)];if(null!=c)a=c.h?c.h(a,b):c.call(null,a,b);else if(c=za._,null!=c)a=c.h?c.h(a,b):c.call(null,a,b);else throw x("IWithMeta.-with-meta",a);}return a},Aa=function(){},Ba=function(){},Ca=function(a,b){if(null!=a&&null!=a.gb)a=a.gb(a,b,!0);else{var c=Ca[t(null==
a?null:a)];if(null!=c)a=c.m?c.m(a,b,!0):c.call(null,a,b,!0);else if(c=Ca._,null!=c)a=c.m?c.m(a,b,!0):c.call(null,a,b,!0);else throw x("IKVReduce.-kv-reduce",a);}return a},Da=function(a,b){if(null!=a&&null!=a.J)a=a.J(a,b);else{var c=Da[t(null==a?null:a)];if(null!=c)a=c.h?c.h(a,b):c.call(null,a,b);else if(c=Da._,null!=c)a=c.h?c.h(a,b):c.call(null,a,b);else throw x("IEquiv.-equiv",a);}return a},Ea=function(a){if(null!=a&&null!=a.N)a=a.N(a);else{var b=Ea[t(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,
a);else if(b=Ea._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw x("IHash.-hash",a);}return a},Fa=function(){},Ga=function(a){if(null!=a&&null!=a.I)a=a.I(a);else{var b=Ga[t(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=Ga._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw x("ISeqable.-seq",a);}return a},Ha=function(){},Ia=function(){},Ja=function(){},E=function(a,b){if(null!=a&&null!=a.vb)a=a.vb(a,b);else{var c=E[t(null==a?null:a)];if(null!=c)a=c.h?c.h(a,b):c.call(null,a,b);else if(c=
E._,null!=c)a=c.h?c.h(a,b):c.call(null,a,b);else throw x("IWriter.-write",a);}return a},Ka=function(){},La=function(a,b,c){if(null!=a&&null!=a.K)a=a.K(a,b,c);else{var d=La[t(null==a?null:a)];if(null!=d)a=d.m?d.m(a,b,c):d.call(null,a,b,c);else if(d=La._,null!=d)a=d.m?d.m(a,b,c):d.call(null,a,b,c);else throw x("IPrintWithWriter.-pr-writer",a);}return a},Ma=function(a){if(null!=a&&null!=a.Xa)a=a.Xa(a);else{var b=Ma[t(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=Ma._,null!=b)a=b.g?
b.g(a):b.call(null,a);else throw x("IEditableCollection.-as-transient",a);}return a},Na=function(a,b){if(null!=a&&null!=a.Za)a=a.Za(a,b);else{var c=Na[t(null==a?null:a)];if(null!=c)a=c.h?c.h(a,b):c.call(null,a,b);else if(c=Na._,null!=c)a=c.h?c.h(a,b):c.call(null,a,b);else throw x("ITransientCollection.-conj!",a);}return a},Oa=function(a){if(null!=a&&null!=a.ib)a=a.ib(a);else{var b=Oa[t(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=Oa._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw x("ITransientCollection.-persistent!",
a);}return a},Pa=function(a,b,c){if(null!=a&&null!=a.Va)a=a.Va(a,b,c);else{var d=Pa[t(null==a?null:a)];if(null!=d)a=d.m?d.m(a,b,c):d.call(null,a,b,c);else if(d=Pa._,null!=d)a=d.m?d.m(a,b,c):d.call(null,a,b,c);else throw x("ITransientAssociative.-assoc!",a);}return a},Qa=function(a){if(null!=a&&null!=a.rb)a=a.rb(a);else{var b=Qa[t(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=Qa._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw x("IChunk.-drop-first",a);}return a},Ra=function(a){if(null!=
a&&null!=a.mb)a=a.mb(a);else{var b=Ra[t(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=Ra._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw x("IChunkedSeq.-chunked-first",a);}return a},Sa=function(a){if(null!=a&&null!=a.fb)a=a.fb(a);else{var b=Sa[t(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=Sa._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw x("IChunkedSeq.-chunked-rest",a);}return a},Ta=function(){},Ua=function(a){if(null!=a&&null!=a.sa)a=a.sa(a);else{var b=
Ua[t(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=Ua._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw x("IIterable.-iterator",a);}return a},Va=function(a){this.Mb=a;this.j=1073741824;this.A=0},bb=function(a){var b=new ba;a.K(null,new Va(b),new Wa(null,5,[Xa,!0,Ya,!0,Za,!1,$a,!1,ab,null],null));return y.g(b)},db=function(a){a=cb(a|0,-862048943);return cb(a<<15|a>>>-15,461845907)},eb=function(a,b){a=(a|0)^(b|0);return cb(a<<13|a>>>-13,5)+-430675100|0},fb=function(a,b){a=(a|0)^b;
a=cb(a^a>>>16,-2048144789);a=cb(a^a>>>13,-1028477387);return a^a>>>16},gb=function(a){a:{var b=1;for(var c=0;;)if(b<a.length)c=eb(c,db(a.charCodeAt(b-1)|a.charCodeAt(b)<<16)),b+=2;else{b=c;break a}}return fb(1===(a.length&1)?b^db(a.charCodeAt(a.length-1)):b,cb(2,a.length))},jb=function(a){255<hb&&(ib={},hb=0);if(null==a)return 0;var b=ib[a];if("number"===typeof b)a=b;else{a:if(null!=a)if(b=a.length,0<b)for(var c=0,d=0;;)if(c<b)d=cb(31,d)+a.charCodeAt(c),c+=1;else{b=d;break a}else b=0;else b=0;ib[a]=
b;hb+=1;a=b}return a},kb=function(a){if(null!=a&&(a.j&4194304||G===a.Qb))return a.N(null)^0;if("number"===typeof a){if(isFinite(a)){if(Number.isSafeInteger(a))a=Math.floor(a)%2147483647;else{var b=new Float64Array(1);b[0]=a;b=b.buffer;a=(new DataView(b,0,4)).getInt32();b=(new DataView(b,4,4)).getInt32();a^=b}return a}switch(a){case Infinity:return 2146435072;case -Infinity:return-1048576;default:return 2146959360}}else return!0===a?a=1231:!1===a?a=1237:"string"===typeof a?(a=jb(a),a=0===a?a:fb(eb(0,
db(a)),4)):a=a instanceof Date?a.valueOf()^0:null==a?0:Ea(a)^0,a},lb=function(a,b){return a^b+2654435769+(a<<6)+(a>>2)},mb=function(a,b,c,d,e){this.eb=a;this.name=b;this.Aa=c;this.Ta=d;this.ra=e;this.j=2154168321;this.A=4096},nb=function(a){return null!=a?a.A&131072||G===a.Rb?!0:a.A?!1:v(Ta,a):v(Ta,a)},I=function(a){if(null==a)return null;if(null!=a&&(a.j&8388608||G===a.Jb))return a.I(null);if(da(a)||"string"===typeof a)return 0===a.length?null:new H(a,0,null);if(null!=a&&null!=a[ob])return a=(null!==
a&&ob in a?a[ob]:void 0).call(a),pb.g?pb.g(a):pb.call(null,a);if(v(Fa,a))return Ga(a);throw Error([y.g(a)," is not ISeqable"].join(""));},J=function(a){if(null==a)return null;if(null!=a&&(a.j&64||G===a.hb))return a.aa(null);a=I(a);return null==a?null:C(a)},qb=function(a){return null!=a?null!=a&&(a.j&64||G===a.hb)?a.fa(null):(a=I(a))?a.fa(null):M:M},N=function(a){return null==a?null:null!=a&&(a.j&128||G===a.Ya)?a.X():I(qb(a))},rb=function(a){this.C=a},O=function(a){return new rb(I(a))},sb=function(a,
b){this.value=a;this.wb=b;this.jb=null;this.j=8388672;this.A=0},pb=function(a){var b=a.next();return u(b.done)?null:new sb(b.value,a)},tb=function(a){var b=0,c=1;for(a=I(a);;)if(null!=a)b+=1,c=cb(31,c)+kb(J(a))|0,a=N(a);else return fb(eb(0,db(c)),b)},ub=function(a){var b=0,c=0;for(a=I(a);;)if(null!=a)b+=1,c=c+kb(J(a))|0,a=N(a);else return fb(eb(0,db(c)),b)},vb=function(){this.G=!1;this.j=32768;this.A=0},wb=function(a){return a instanceof vb},xb=function(a){return wa(a)},yb=function(a,b){var c=a.length;
if(0===a.length)return b.F?b.F():b.call(null);for(var d=a[0],e=1;;)if(e<c){var g=a[e];d=b.h?b.h(d,g):b.call(null,d,g);if(wb(d))return wa(d);e+=1}else return d},zb=function(a,b,c){var d=a.length,e=c;for(c=0;;)if(c<d){var g=a[c];e=b.h?b.h(e,g):b.call(null,e,g);if(wb(e))return wa(e);c+=1}else return e},Ab=function(a,b,c,d){for(var e=a.length;;)if(d<e){var g=a[d];c=b.h?b.h(c,g):b.call(null,c,g);if(wb(c))return wa(c);d+=1}else return c},Bb=function(a){return null!=a?a.j&2||G===a.zb?!0:a.j?!1:v(fa,a):v(fa,
a)},Cb=function(a){return null!=a?a.j&16||G===a.tb?!0:a.j?!1:v(la,a):v(la,a)},S=function(a,b,c){var d=Q.g?Q.g(a):Q.call(null,a);if(c>=d)return-1;!(0<c)&&0>c&&(c+=d,c=0>c?0:c);for(;;)if(c<d){if(R.h(Db?Db(a,c):Eb.call(null,a,c),b))return c;c+=1}else return-1},T=function(a,b,c){var d=Q.g?Q.g(a):Q.call(null,a);if(0===d)return-1;0<c?(--d,c=d<c?d:c):c=0>c?d+c:c;for(;;)if(0<=c){if(R.h(Db?Db(a,c):Eb.call(null,a,c),b))return c;--c}else return-1},Fb=function(a,b){this.i=a;this.o=b},H=function(a,b,c){this.i=
a;this.o=b;this.u=c;this.j=166592766;this.A=401408},Gb=function(a){return 0<a.length?new H(a,0,null):null},Q=function(a){if(null!=a)if(null!=a&&(a.j&2||G===a.zb))a=a.U(null);else if(da(a))a=a.length;else if("string"===typeof a)a=a.length;else if(null!=a&&(a.j&8388608||G===a.Jb))a:{a=I(a);for(var b=0;;){if(Bb(a)){a=b+ha(a);break a}a=N(a);b+=1}}else a=ha(a);else a=0;return a},Hb=function(a,b,c){for(;;){if(null==a)return c;if(0===b)return I(a)?J(a):c;if(Cb(a))return U(a,b,c);if(I(a))a=N(a),--b;else return c}},
Eb=function(a){switch(arguments.length){case 2:return Db(arguments[0],arguments[1]);case 3:return Ib(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",y.g(arguments.length)].join(""));}},Db=function(a,b){if("number"!==typeof b)throw Error("Index argument to nth must be a number");if(null==a)return a;if(null!=a&&(a.j&16||G===a.tb))return a.ea(null,b);if(da(a)){if(-1<b&&b<a.length)return a[b|0];throw Error("Index out of bounds");}if("string"===typeof a){if(-1<b&&b<a.length)return a.charAt(b|
0);throw Error("Index out of bounds");}if(null!=a&&(a.j&64||G===a.hb)||null!=a&&(a.j&16777216||G===a.ub)){if(0>b)throw Error("Index out of bounds");a:for(;;){if(null==a)throw Error("Index out of bounds");if(0===b){if(I(a)){a=J(a);break a}throw Error("Index out of bounds");}if(Cb(a)){a=U(a,b);break a}if(I(a))a=N(a),--b;else throw Error("Index out of bounds");}return a}if(v(la,a))return U(a,b);throw Error(["nth not supported on this type ",y.g(ea(null==a?null:a.constructor))].join(""));},Ib=function(a,
b,c){if("number"!==typeof b)throw Error("Index argument to nth must be a number.");if(null==a)return c;if(null!=a&&(a.j&16||G===a.tb))return a.la(null,b,c);if(da(a))return-1<b&&b<a.length?a[b|0]:c;if("string"===typeof a)return-1<b&&b<a.length?a.charAt(b|0):c;if(null!=a&&(a.j&64||G===a.hb)||null!=a&&(a.j&16777216||G===a.ub))return 0>b?c:Hb(a,b,c);if(v(la,a))return U(a,b,c);throw Error(["nth not supported on this type ",y.g(ea(null==a?null:a.constructor))].join(""));},Lb=function(a){switch(arguments.length){case 2:return Jb(arguments[0],
arguments[1]);case 3:return Kb(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",y.g(arguments.length)].join(""));}},Jb=function(a,b){return null==a?null:null!=a&&(a.j&256||G===a.Db)?a.ka(null,b):da(a)?null!=b&&b<a.length?a[b|0]:null:"string"===typeof a?null!=b&&-1<b&&b<a.length?a.charAt(b|0):null:v(na,a)?Mb(a,b):null},Kb=function(a,b,c){return null!=a?null!=a&&(a.j&256||G===a.Db)?a.H(null,b,c):da(a)?null!=b&&-1<b&&b<a.length?a[b|0]:c:"string"===typeof a?null!=b&&-1<b&&
b<a.length?a.charAt(b|0):c:v(na,a)?Mb(a,b,c):c:c},Nb=function(a,b){this.s=a;this.u=b;this.j=393217;this.A=0},Ob=function(a,b){return"function"===typeof a?new Nb(a,b):null==a?null:za(a,b)},Pb=function(a){var b=null!=a;return(b?null!=a?a.j&131072||G===a.Gb||(a.j?0:v(xa,a)):v(xa,a):b)?ya(a):null},Qb=function(a){return null!=a?a.j&16777216||G===a.ub?!0:a.j?!1:v(Ha,a):v(Ha,a)},Rb=function(a){return null==a?!1:null!=a?a.j&1024||G===a.Tb?!0:a.j?!1:v(ra,a):v(ra,a)},Sb=function(a){return null!=a?a.j&67108864||
G===a.Vb?!0:a.j?!1:v(Ja,a):v(Ja,a)},Tb=function(a){return null!=a?a.j&16384||G===a.Wb?!0:a.j?!1:v(va,a):v(va,a)},Ub=function(a){return null!=a?a.A&512||G===a.Ob?!0:!1:!1},Vb=function(a,b,c,d,e){for(;;){if(0===e)return c;c[d]=a[b];d+=1;--e;b+=1}},Wb=function(a){return null==a?!1:!1===a?!1:!0},Yb=function(a,b){return null!=a&&(a.j&512||G===a.yb)?a.Ua(null,b):v(oa,a)?pa(a,b):Kb(a,b,Xb)===Xb?!1:!0},ac=function(a,b){var c=I(b);return c?(b=J(c),c=N(c),Zb?Zb(a,b,c):$b.call(null,a,b,c)):a.F?a.F():a.call(null)},
bc=function(a,b,c){for(c=I(c);;)if(c){var d=J(c);b=a.h?a.h(b,d):a.call(null,b,d);if(wb(b))return wa(b);c=N(c)}else return b},cc=function(a,b){a=Ua(a);if(u(a.ia()))for(var c=a.next();;)if(a.ia()){var d=a.next();c=b.h?b.h(c,d):b.call(null,c,d);if(wb(c))return wa(c)}else return c;else return b.F?b.F():b.call(null)},dc=function(a,b,c){for(a=Ua(a);;)if(a.ia()){var d=a.next();c=b.h?b.h(c,d):b.call(null,c,d);if(wb(c))return wa(c)}else return c},$b=function(a){switch(arguments.length){case 2:var b=arguments[0],
c=arguments[1];return null!=c&&(c.j&524288||G===c.Ib)?c.Z(null,b):da(c)?yb(c,b):"string"===typeof c?yb(c,b):v(Aa,c)?ec(c,b):nb(c)?cc(c,b):ac(b,c);case 3:return Zb(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",y.g(arguments.length)].join(""));}},Zb=function(a,b,c){return null!=c&&(c.j&524288||G===c.Ib)?c.$(null,a,b):da(c)?zb(c,a,b):"string"===typeof c?zb(c,a,b):v(Aa,c)?ec(c,a,b):nb(c)?dc(c,a,b):bc(a,b,c)},fc=function(a,b){return(null!=b?b.j&1048576||G===b.Cb||(b.j?
0:v(Ba,b)):v(Ba,b))?Ca(b,a):Zb(function(c,d){var e=sa(d);d=ua(d);return a.m?a.m(c,e,d):a.call(null,c,e,d)},!0,b)},gc=function(a){return a},hc=function(a){a=(a-a%2)/2;return 0<=a?Math.floor(a):Math.ceil(a)},ic=function(a){a-=a>>1&1431655765;a=(a&858993459)+(a>>2&858993459);return 16843009*(a+(a>>4)&252645135)>>24},jc=function(a,b){if(Qb(b))if(Bb(a)&&Bb(b)&&Q(a)!==Q(b))a=!1;else a:for(a=I(a),b=I(b);;){if(null==a){a=null==b;break a}if(null!=b&&R.h(J(a),J(b)))a=N(a),b=N(b);else{a=!1;break a}}else a=null;
return Wb(a)},kc=function(a,b,c,d,e){this.u=a;this.first=b;this.wa=c;this.count=d;this.v=e;this.j=65937646;this.A=8192},lc=function(a){this.u=a;this.j=65937614;this.A=8192},mc=function(a,b,c,d){this.u=a;this.first=b;this.wa=c;this.v=d;this.j=65929452;this.A=8192},V=function(a,b){return null==b?new kc(null,a,null,1,null):null!=b&&(b.j&64||G===b.hb)?new mc(null,a,b,null):new mc(null,a,I(b),null)},W=function(a,b,c,d){this.eb=a;this.name=b;this.va=c;this.Ta=d;this.j=2153775105;this.A=4096},nc=function(a){if(null!=
a&&(a.A&4096||G===a.Hb))return a.eb;throw Error(["Doesn't support namespace: ",y.g(a)].join(""));},oc=function(a,b,c){this.u=a;this.$a=b;this.C=null;this.v=c;this.j=32374988;this.A=1},pc=function(a){null!=a.$a&&(a.C=a.$a.F?a.$a.F():a.$a.call(null),a.$a=null);return a.C},qc=function(a){this.lb=a;this.end=0;this.j=2;this.A=0},rc=function(a,b,c){this.i=a;this.R=b;this.end=c;this.j=524306;this.A=0},sc=function(a,b,c,d){this.ta=a;this.oa=b;this.u=c;this.v=d;this.j=31850732;this.A=1536},tc=function(a,b){return 0===
ha(a)?b:new sc(a,b,null,null)},uc=function(a,b){a.add(b)},vc=function(a,b){if(Bb(b))return Q(b);var c=0;for(b=I(b);;)if(null!=b&&c<a)c+=1,b=N(b);else return c},wc=function(a,b,c){var d=I(c);if(0===b)return a.F?a.F():a.call(null);c=C(d);var e=D(d);if(1===b)return a.g?a.g(c):a.call(null,c);d=C(e);var g=D(e);if(2===b)return a.h?a.h(c,d):a.call(null,c,d);e=C(g);var h=D(g);if(3===b)return a.m?a.m(c,d,e):a.call(null,c,d,e);g=C(h);var k=D(h);if(4===b)return a.W?a.W(c,d,e,g):a.call(null,c,d,e,g);h=C(k);var l=
D(k);if(5===b)return a.ua?a.ua(c,d,e,g,h):a.call(null,c,d,e,g,h);k=C(l);var m=D(l);if(6===b)return a.Na?a.Na(c,d,e,g,h,k):a.call(null,c,d,e,g,h,k);l=C(m);var n=D(m);if(7===b)return a.Oa?a.Oa(c,d,e,g,h,k,l):a.call(null,c,d,e,g,h,k,l);m=C(n);var p=D(n);if(8===b)return a.Pa?a.Pa(c,d,e,g,h,k,l,m):a.call(null,c,d,e,g,h,k,l,m);n=C(p);var q=D(p);if(9===b)return a.Qa?a.Qa(c,d,e,g,h,k,l,m,n):a.call(null,c,d,e,g,h,k,l,m,n);p=C(q);var r=D(q);if(10===b)return a.Ca?a.Ca(c,d,e,g,h,k,l,m,n,p):a.call(null,c,d,e,
g,h,k,l,m,n,p);q=C(r);var w=D(r);if(11===b)return a.Da?a.Da(c,d,e,g,h,k,l,m,n,p,q):a.call(null,c,d,e,g,h,k,l,m,n,p,q);r=C(w);var A=D(w);if(12===b)return a.Ea?a.Ea(c,d,e,g,h,k,l,m,n,p,q,r):a.call(null,c,d,e,g,h,k,l,m,n,p,q,r);w=C(A);var B=D(A);if(13===b)return a.Fa?a.Fa(c,d,e,g,h,k,l,m,n,p,q,r,w):a.call(null,c,d,e,g,h,k,l,m,n,p,q,r,w);A=C(B);var F=D(B);if(14===b)return a.Ga?a.Ga(c,d,e,g,h,k,l,m,n,p,q,r,w,A):a.call(null,c,d,e,g,h,k,l,m,n,p,q,r,w,A);B=C(F);var K=D(F);if(15===b)return a.Ha?a.Ha(c,d,e,
g,h,k,l,m,n,p,q,r,w,A,B):a.call(null,c,d,e,g,h,k,l,m,n,p,q,r,w,A,B);F=C(K);var P=D(K);if(16===b)return a.Ia?a.Ia(c,d,e,g,h,k,l,m,n,p,q,r,w,A,B,F):a.call(null,c,d,e,g,h,k,l,m,n,p,q,r,w,A,B,F);K=C(P);var ca=D(P);if(17===b)return a.Ja?a.Ja(c,d,e,g,h,k,l,m,n,p,q,r,w,A,B,F,K):a.call(null,c,d,e,g,h,k,l,m,n,p,q,r,w,A,B,F,K);P=C(ca);var ta=D(ca);if(18===b)return a.Ka?a.Ka(c,d,e,g,h,k,l,m,n,p,q,r,w,A,B,F,K,P):a.call(null,c,d,e,g,h,k,l,m,n,p,q,r,w,A,B,F,K,P);ca=C(ta);ta=D(ta);if(19===b)return a.La?a.La(c,d,
e,g,h,k,l,m,n,p,q,r,w,A,B,F,K,P,ca):a.call(null,c,d,e,g,h,k,l,m,n,p,q,r,w,A,B,F,K,P,ca);var Dd=C(ta);D(ta);if(20===b)return a.Ma?a.Ma(c,d,e,g,h,k,l,m,n,p,q,r,w,A,B,F,K,P,ca,Dd):a.call(null,c,d,e,g,h,k,l,m,n,p,q,r,w,A,B,F,K,P,ca,Dd);throw Error("Only up to 20 arguments supported on functions");},xc=function(a){return null!=a&&(a.j&128||G===a.Ya)?a.X():I(qb(a))},zc=function(a,b,c){return null==c?a.g?a.g(b):a.call(a,b):yc(a,b,C(c),xc(c))},yc=function(a,b,c,d){return null==d?a.h?a.h(b,c):a.call(a,b,c):
Ac(a,b,c,C(d),xc(d))},Ac=function(a,b,c,d,e){return null==e?a.m?a.m(b,c,d):a.call(a,b,c,d):Bc(a,b,c,d,C(e),xc(e))},Bc=function(a,b,c,d,e,g){if(null==g)return a.W?a.W(b,c,d,e):a.call(a,b,c,d,e);var h=C(g),k=N(g);if(null==k)return a.ua?a.ua(b,c,d,e,h):a.call(a,b,c,d,e,h);g=C(k);var l=N(k);if(null==l)return a.Na?a.Na(b,c,d,e,h,g):a.call(a,b,c,d,e,h,g);k=C(l);var m=N(l);if(null==m)return a.Oa?a.Oa(b,c,d,e,h,g,k):a.call(a,b,c,d,e,h,g,k);l=C(m);var n=N(m);if(null==n)return a.Pa?a.Pa(b,c,d,e,h,g,k,l):a.call(a,
b,c,d,e,h,g,k,l);m=C(n);var p=N(n);if(null==p)return a.Qa?a.Qa(b,c,d,e,h,g,k,l,m):a.call(a,b,c,d,e,h,g,k,l,m);n=C(p);var q=N(p);if(null==q)return a.Ca?a.Ca(b,c,d,e,h,g,k,l,m,n):a.call(a,b,c,d,e,h,g,k,l,m,n);p=C(q);var r=N(q);if(null==r)return a.Da?a.Da(b,c,d,e,h,g,k,l,m,n,p):a.call(a,b,c,d,e,h,g,k,l,m,n,p);q=C(r);var w=N(r);if(null==w)return a.Ea?a.Ea(b,c,d,e,h,g,k,l,m,n,p,q):a.call(a,b,c,d,e,h,g,k,l,m,n,p,q);r=C(w);var A=N(w);if(null==A)return a.Fa?a.Fa(b,c,d,e,h,g,k,l,m,n,p,q,r):a.call(a,b,c,d,
e,h,g,k,l,m,n,p,q,r);w=C(A);var B=N(A);if(null==B)return a.Ga?a.Ga(b,c,d,e,h,g,k,l,m,n,p,q,r,w):a.call(a,b,c,d,e,h,g,k,l,m,n,p,q,r,w);A=C(B);var F=N(B);if(null==F)return a.Ha?a.Ha(b,c,d,e,h,g,k,l,m,n,p,q,r,w,A):a.call(a,b,c,d,e,h,g,k,l,m,n,p,q,r,w,A);B=C(F);var K=N(F);if(null==K)return a.Ia?a.Ia(b,c,d,e,h,g,k,l,m,n,p,q,r,w,A,B):a.call(a,b,c,d,e,h,g,k,l,m,n,p,q,r,w,A,B);F=C(K);var P=N(K);if(null==P)return a.Ja?a.Ja(b,c,d,e,h,g,k,l,m,n,p,q,r,w,A,B,F):a.call(a,b,c,d,e,h,g,k,l,m,n,p,q,r,w,A,B,F);K=C(P);
var ca=N(P);if(null==ca)return a.Ka?a.Ka(b,c,d,e,h,g,k,l,m,n,p,q,r,w,A,B,F,K):a.call(a,b,c,d,e,h,g,k,l,m,n,p,q,r,w,A,B,F,K);P=C(ca);var ta=N(ca);if(null==ta)return a.La?a.La(b,c,d,e,h,g,k,l,m,n,p,q,r,w,A,B,F,K,P):a.call(a,b,c,d,e,h,g,k,l,m,n,p,q,r,w,A,B,F,K,P);ca=C(ta);ta=N(ta);if(null==ta)return a.Ma?a.Ma(b,c,d,e,h,g,k,l,m,n,p,q,r,w,A,B,F,K,P,ca):a.call(a,b,c,d,e,h,g,k,l,m,n,p,q,r,w,A,B,F,K,P,ca);b=[b,c,d,e,h,g,k,l,m,n,p,q,r,w,A,B,F,K,P,ca];for(c=ta;;)if(c)b.push(C(c)),c=N(c);else break;return a.apply(a,
b)},Fc=function(a){switch(arguments.length){case 2:return Cc(arguments[0],arguments[1]);case 3:return Dc(arguments[0],arguments[1],arguments[2]);case 4:var b=arguments[0];var c=arguments[1],d=arguments[2],e=arguments[3];b.ba?(c=V(c,V(d,e)),d=b.ga,e=2+vc(d-1,e),b=e<=d?wc(b,e,c):b.ba(c)):b=yc(b,c,d,I(e));return b;case 5:b=arguments[0];c=arguments[1];d=arguments[2];var g=arguments[3];e=arguments[4];b.ba?(c=V(c,V(d,V(g,e))),d=b.ga,e=3+vc(d-2,e),b=e<=d?wc(b,e,c):b.ba(c)):b=Ac(b,c,d,g,I(e));return b;default:e=
[];b=arguments.length;for(c=0;;)if(c<b)e.push(arguments[c]),c+=1;else break;b=arguments[0];c=arguments[1];d=arguments[2];g=arguments[3];var h=arguments[4];e=5<e.length?new H(e.slice(5),0,null):null;b.ba?(e=Ec(e),c=V(c,V(d,V(g,V(h,e)))),d=b.ga,e=4+vc(d-3,e),b=e<=d?wc(b,e,c):b.ba(c)):b=Bc(b,c,d,g,h,Ec(e));return b}},Cc=function(a,b){if(a.ba){var c=a.ga,d=vc(c+1,b);return d<=c?wc(a,d,b):a.ba(b)}b=I(b);return null==b?a.F?a.F():a.call(a):zc(a,C(b),xc(b))},Dc=function(a,b,c){if(a.ba){b=V(b,c);var d=a.ga;
c=vc(d,c)+1;return c<=d?wc(a,c,b):a.ba(b)}return zc(a,b,I(c))},Gc=function(a){this.Lb=a;this.j=393216;this.A=0},Hc=function(a,b){for(;;){if(null==I(b))return!0;var c=J(b);c=a.g?a.g(c):a.call(null,c);if(u(c))b=N(b);else return!1}},Jc=function(a,b){return null!=a?null!=a&&(a.A&4||G===a.Pb)?za(Oa(Zb(Na,Ma(a),b)),Pb(a)):Zb(ka,a,b):Zb(Ic,a,b)},Kc=function(a,b){this.D=a;this.i=b},Lc=function(a){return new Kc(a,[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,
null,null,null,null,null,null,null,null,null,null,null,null,null])},Mc=function(a){a=a.l;return 32>a?0:a-1>>>5<<5},Nc=function(a,b,c){for(;;){if(0===b)return c;var d=Lc(a);d.i[0]=c;c=d;b-=5}},Oc=function(a,b){if(b>=Mc(a))return a.da;var c=a.root;for(a=a.shift;;)if(0<a){var d=a-5;c=c.i[b>>>a&31];a=d}else return c.i},Pc=function(a,b){if(0<=b&&b<a.l)b=Oc(a,b);else throw a=a.l,Error(["No item ",y.g(b)," in vector of length ",y.g(a)].join(""));return b},Qc=function(a,b,c){this.kb=this.o=0;this.i=a;this.Nb=
b;this.start=0;this.end=c},Sc=function(a,b,c,d){return c<d?Rc(a,b,Db(a,c),c+1,d):b.F?b.F():b.call(null)},Rc=function(a,b,c,d,e){var g=c;c=d;for(d=Oc(a,d);;)if(c<e){var h=c&31;d=0===h?Oc(a,c):d;h=d[h];g=b.h?b.h(g,h):b.call(null,g,h);if(wb(g))return wa(g);c+=1}else return g},X=function(a,b,c,d,e,g){this.u=a;this.l=b;this.shift=c;this.root=d;this.da=e;this.v=g;this.j=167666463;this.A=401412},Tc=function(a,b,c,d,e){this.ja=a;this.node=b;this.o=c;this.R=d;this.u=e;this.v=null;this.j=32375020;this.A=263680},
Wc=function(a){switch(arguments.length){case 3:var b=arguments[0],c=arguments[1],d=arguments[2];return new Tc(b,Pc(b,c),c,d,null);case 4:return Uc(arguments[0],arguments[1],arguments[2],arguments[3]);case 5:return Vc(arguments[0],arguments[1],arguments[2],arguments[3],arguments[4]);default:throw Error(["Invalid arity: ",y.g(arguments.length)].join(""));}},Uc=function(a,b,c,d){return new Tc(a,b,c,d,null)},Vc=function(a,b,c,d,e){return new Tc(a,b,c,d,e)},Xc=function(a,b){return a===b.D?b:new Kc(a,z(b.i))},
Yc=function(a){return new Kc({},z(a.i))},Zc=function(a){var b=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];Vb(a,0,b,0,a.length);return b},$c=function(a,b,c,d){this.l=a;this.shift=b;this.root=c;this.da=d;this.A=88;this.j=275},ad=function(a,b,c){if(a.root.D){if(0<=b&&b<a.l){if(Mc(a)<=b)a.da[b&31]=c;else{var d=function k(g,h){h=Xc(a.root.D,h);if(0===g)h.i[b&31]=c;else{var l=b>>>g&31;g=
k(g-5,h.i[l]);h.i[l]=g}return h}(a.shift,a.root);a.root=d}return a}if(b===a.l)return a.Za(null,c);throw Error(["Index ",y.g(b)," out of bounds for TransientVector of length",y.g(a.l)].join(""));}throw Error("assoc! after persistent!");},bd=function(){this.j=2097152;this.A=0},dd=function(a,b){return Wb(Rb(b)&&!Sb(b)?Q(a)===Q(b)?(null!=a?a.j&1048576||G===a.Cb||(a.j?0:v(Ba,a)):v(Ba,a))?fc(function(c,d,e){return R.h(Kb(b,d,cd),e)?!0:new vb},a):Hc(function(c){return R.h(Kb(b,J(c),cd),J(N(c)))},a):null:
null)},ed=function(a){this.C=a},fd=function(a,b){if(b instanceof W)a:{var c=a.length;b=b.va;for(var d=0;;){if(c<=d){a=-1;break a}if(a[d]instanceof W&&b===a[d].va){a=d;break a}d+=2}}else if("string"===typeof b||"number"===typeof b)a:for(c=a.length,d=0;;){if(c<=d){a=-1;break a}if(b===a[d]){a=d;break a}d+=2}else if(b instanceof mb)a:for(c=a.length,b=b.Aa,d=0;;){if(c<=d){a=-1;break a}if(a[d]instanceof mb&&b===a[d].Aa){a=d;break a}d+=2}else if(null==b)a:for(b=a.length,c=0;;){if(b<=c){a=-1;break a}if(null==
a[c]){a=c;break a}c+=2}else a:for(c=a.length,d=0;;){if(c<=d){a=-1;break a}if(R.h(b,a[d])){a=d;break a}d+=2}return a},gd=function(a,b){this.key=a;this.G=b;this.v=null;this.j=166619935;this.A=0},hd=function(a){return null!=a?a.j&2048||G===a.Ub?!0:!1:!1},id=function(a,b,c){this.i=a;this.o=b;this.ra=c;this.j=32374990;this.A=262144},jd=function(a,b){this.i=a;this.o=0;this.l=b},Wa=function(a,b,c,d){this.u=a;this.l=b;this.i=c;this.v=d;this.j=16647951;this.A=401412},kd=function(a,b){return a===b?!0:a===b||
a instanceof W&&b instanceof W&&a.va===b.va?!0:R.h(a,b)},ld=function(a){for(var b=0,c=0;;)if(b<a.length){var d;a:for(d=0;;)if(d<b){var e=kd(a[b],a[d]);if(e){d=e;break a}d=2+d}else{d=!1;break a}c=d?c:c+2;b=2+b}else return c},md=function(a,b){var c=a.length-1,d=I(b);b=Array(c+2*Q(d));a=Vb(a,0,b,0,c);for(b=c;;)if(d){var e=J(d);a[b]=sa(e);a[b+1]=ua(e);b=2+c;d=N(d)}else return a},od=function(a,b){var c=b?md(a,Jc(nd,a[a.length-1])):a;a=ld(c);var d=c.length;if(a<d){a=Array(a);for(var e=0,g=0;;)if(e<d)(function(){for(var h=
0;;)if(h<g){var k=kd(c[e],c[h]);if(k)return k;h=2+h}else return!1})()?(b=g,e=2+e,g=b):(b=function(){for(var h=d-2;;)if(h>=e){if(kd(c[e],c[h]))return h;h-=2}else return h}(),a[g]=c[e],a[g+1]=c[b+1],b=2+g,e=2+e,g=b);else break;return new Wa(null,a.length/2,a,null)}return new Wa(null,c.length/2,c,null)},pd=function(a,b){this.Wa={};this.Sa=a;this.i=b;this.j=259;this.A=56},rd=function(a,b){for(var c=Ma(qd),d=0;;)if(d<a)c=Pa(c,b[d],b[d+1]),d+=2;else return c},sd=function(){this.G=!1},td=function(a,b,c){a=
z(a);a[b]=c;return a},ud=function(a,b,c,d){a=a.Ra(b);a.i[c]=d;return a},vd=function(a,b,c){for(var d=a.length,e=0,g=c;;)if(e<d){c=a[e];if(null!=c){var h=a[e+1];c=b.m?b.m(g,c,h):b.call(null,g,c,h)}else c=a[e+1],c=null!=c?c.bb(b,g):g;if(wb(c))return c;e+=2;g=c}else return g},wd=function(a){this.i=a;this.o=0;this.pa=this.cb=null},xd=function(a,b,c){this.D=a;this.M=b;this.i=c;this.A=131072;this.j=0},yd=function(a){this.i=a;this.o=0;this.pa=null},zd=function(a,b,c){this.D=a;this.l=b;this.i=c;this.A=131072;
this.j=0},Ad=function(a,b,c){b*=2;for(var d=0;;)if(d<b){if(kd(c,a[d]))return d;d+=2}else return-1},Bd=function(a,b,c,d){this.D=a;this.ya=b;this.l=c;this.i=d;this.A=131072;this.j=0},Fd=function(a){switch(arguments.length){case 6:return Cd(arguments[0],arguments[1],arguments[2],arguments[3],arguments[4],arguments[5]);case 7:return Ed(arguments[0],arguments[1],arguments[2],arguments[3],arguments[4],arguments[5],arguments[6]);default:throw Error(["Invalid arity: ",y.g(arguments.length)].join(""));}},
Cd=function(a,b,c,d,e,g){var h=kb(b);if(h===d)return new Bd(null,h,2,[b,c,e,g]);var k=new sd;return Gd.ma(a,h,b,c,k).ma(a,d,e,g,k)},Ed=function(a,b,c,d,e,g,h){var k=kb(c);if(k===e)return new Bd(null,k,2,[c,d,g,h]);var l=new sd;return Gd.na(a,b,k,c,d,l).na(a,b,e,g,h,l)},Hd=function(a,b,c,d,e){this.u=a;this.qa=b;this.o=c;this.C=d;this.v=e;this.j=32374988;this.A=0},Kd=function(a){switch(arguments.length){case 1:return Id(arguments[0]);case 3:return Jd(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",
y.g(arguments.length)].join(""));}},Id=function(a){return Jd(a,0,null)},Jd=function(a,b,c){if(null==c)for(c=a.length;;)if(b<c){if(null!=a[b])return new Hd(null,a,b,null,null);var d=a[b+1];if(u(d)&&(d=d.ab(),u(d)))return new Hd(null,a,b+2,d,null);b+=2}else return null;else return new Hd(null,a,b,c,null)},Ld=function(a,b,c,d,e){this.u=a;this.qa=b;this.o=c;this.C=d;this.v=e;this.j=32374988;this.A=0},Od=function(a){switch(arguments.length){case 1:return Md(arguments[0]);case 3:return Nd(arguments[0],
arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",y.g(arguments.length)].join(""));}},Md=function(a){return Nd(a,0,null)},Nd=function(a,b,c){if(null==c)for(c=a.length;;)if(b<c){var d=a[b];if(u(d)&&(d=d.ab(),u(d)))return new Ld(null,a,b+1,d,null);b+=1}else return null;else return new Ld(null,a,b,c,null)},Pd=function(a,b){this.ca=a;this.xb=b;this.qb=!1},Qd=function(a,b,c,d,e,g){this.u=a;this.l=b;this.root=c;this.ha=d;this.ca=e;this.v=g;this.j=16123663;this.A=139268},Rd=function(a,b,
c,d){this.D={};this.root=a;this.count=b;this.ha=c;this.ca=d;this.j=259;this.A=56},Sd=function(a,b,c){if(a.D){if(null==b)a.ca!==c&&(a.ca=c),a.ha||(a.count+=1,a.ha=!0);else{var d=new sd;b=(null==a.root?Gd:a.root).na(a.D,0,kb(b),b,c,d);b!==a.root&&(a.root=b);d.G&&(a.count+=1)}return a}throw Error("assoc! after persistent!");},Td=function(a,b){this.B=a;this.ra=b;this.j=32374988;this.A=0},Ud=function(a){return(a=I(a))?new Td(a,null):null},Vd=function(a){return sa(a)},Wd=function(a,b){this.B=a;this.ra=
b;this.j=32374988;this.A=0},Xd=function(a){return(a=I(a))?new Wd(a,null):null},Yd=function(a){return ua(a)},Zd=function(a){if(null!=a&&(a.A&4096||G===a.Hb))return a.name;if("string"===typeof a)return a;throw Error(["Doesn't support name: ",y.g(a)].join(""));},be=function(a,b,c,d,e,g,h){var k=$d;$d=null==$d?null:$d-1;try{if(null!=$d&&0>$d)return E(a,"#");E(a,c);if(0===ab.g(g))I(h)&&E(a,function(){var r=ae.g(g);return u(r)?r:"..."}());else{if(I(h)){var l=J(h);b.m?b.m(l,a,g):b.call(null,l,a,g)}for(var m=
N(h),n=ab.g(g)-1;;)if(!m||null!=n&&0===n){I(m)&&0===n&&(E(a,d),E(a,function(){var r=ae.g(g);return u(r)?r:"..."}()));break}else{E(a,d);var p=J(m);c=a;h=g;b.m?b.m(p,c,h):b.call(null,p,c,h);var q=N(m);c=n-1;m=q;n=c}}return E(a,e)}finally{$d=k}},ce=function(a,b){b=I(b);for(var c=null,d=0,e=0;;)if(e<d){var g=c.ea(null,e);E(a,g);e+=1}else if(b=I(b))c=b,Ub(c)?(b=Ra(c),d=Sa(c),c=b,g=Q(b),b=d,d=g):(g=J(c),E(a,g),b=N(c),c=null,d=0),e=0;else return null},ee=function(a){return['"',y.g(a.replace(RegExp('[\\\\"\b\f\n\r\t]',
"g"),function(b){return de[b]})),'"'].join("")},fe=function(a,b){return(a=Wb(Jb(a,Za)))?(a=null!=b?b.j&131072||G===b.Gb?!0:!1:!1)?null!=Pb(b):a:a},ke=function(a,b,c){if(null==a)return E(b,"nil");if(fe(c,a)){E(b,"^");var d=Pb(a);Y.m?Y.m(d,b,c):Y.call(null,d,b,c);E(b," ")}if(a.Kb)return a.Xb(a,b,c);if(null!=a?a.j&2147483648||G===a.Y||(a.j?0:v(Ka,a)):v(Ka,a))return La(a,b,c);if(!0===a||!1===a)return E(b,y.g(a));if("number"===typeof a)return E(b,isNaN(a)?"##NaN":a===Number.POSITIVE_INFINITY?"##Inf":a===
Number.NEGATIVE_INFINITY?"##-Inf":y.g(a));if(null!=a&&a.constructor===Object)return E(b,"#js "),d=Z.h(function(g){var h=/[A-Za-z_\*\+\?!\-'][\w\*\+\?!\-']*/;if("string"===typeof g)if(h=h.exec(g),null!=h&&R.h(h[0],g))if(1===h.length)h=h[0];else if(u(hd.g?hd.g(h):hd.call(null,h)))h=new X(null,2,5,ge,[Vd.g?Vd.g(h):Vd.call(null,h),Yd.g?Yd.g(h):Yd.call(null,h)],null);else if(Tb(h))h=Ob(h,null);else if(da(h))b:{var k=h.length;if(32>k)h=new X(null,k,5,ge,h,null);else for(var l=32,m=(new X(null,32,5,ge,h.slice(0,
32),null)).Xa(null);;)if(l<k){var n=l+1;m=Na(m,h[l]);l=n}else{h=Oa(m);break b}}else h=Oa(Zb(Na,Ma(he),h));else h=null;else throw new TypeError("re-matches must match against a string.");return new gd(null!=h?ie.g(g):g,a[g])},aa(a)),je.W?je.W(d,Y,b,c):je.call(null,d,Y,b,c);if(da(a))return be(b,Y,"#js ["," ","]",c,a);if("string"===typeof a)return u(Ya.g(c))?E(b,ee(a)):E(b,a);if("function"===typeof a){var e=a.name;c=u(function(){var g=null==e;return g?g:/^[\s\xa0]*$/.test(e)}())?"Function":e;return ce(b,
Gb(["#object[",c,u(!1)?[' "',y.g(a),'"'].join(""):"","]"]))}if(a instanceof Date)return c=function(g,h){for(g=y.g(g);;)if(g.length<h)g=["0",g].join("");else return g},ce(b,Gb(['#inst "',c(a.getUTCFullYear(),4),"-",c(a.getUTCMonth()+1,2),"-",c(a.getUTCDate(),2),"T",c(a.getUTCHours(),2),":",c(a.getUTCMinutes(),2),":",c(a.getUTCSeconds(),2),".",c(a.getUTCMilliseconds(),3),"-",'00:00"']));if(a instanceof RegExp)return ce(b,Gb(['#"',a.source,'"']));if("symbol"===t(a)||"undefined"!==typeof Symbol&&a instanceof
Symbol)return ce(b,Gb(["#object[",a.toString(),"]"]));if(u(function(){var g=null==a?null:a.constructor;return null==g?null:g.pb}()))return ce(b,Gb(["#object[",a.constructor.pb.replace(RegExp("/","g"),"."),"]"]));e=function(){var g=null==a?null:a.constructor;return null==g?null:g.name}();c=u(function(){var g=null==e;return g?g:/^[\s\xa0]*$/.test(e)}())?"Object":e;return null==a.constructor?ce(b,Gb(["#object[",c,"]"])):ce(b,Gb(["#object[",c," ",y.g(a),"]"]))},Y=function(a,b,c){var d=le.g(c);return u(d)?
(c=me.m(c,ne,ke),d.m?d.m(a,b,c):d.call(null,a,b,c)):ke(a,b,c)},pe=function(a){return a instanceof mb?oe.h(null,Zd(a)):ie.h(null,Zd(a))},qe=function(a){if(u(!1)){var b=I(a),c=I(b),d=J(c);N(c);Ib(d,0,null);Ib(d,1,null);c=null==a?null:null!=a&&(a.j&4||G===a.Bb)?a.V(null):(null!=a?a.j&4||G===a.Bb||(a.j?0:v(ia,a)):v(ia,a))?ja(a):null;for(a=null;;){d=a;b=I(b);a=J(b);var e=N(b),g=a;a=Ib(g,0,null);b=Ib(g,1,null);if(u(g))if(a instanceof W||a instanceof mb)if(u(d))if(R.h(d,nc(a)))c=me.m(c,pe(a),b),a=d,b=e;
else return null;else if(d=nc(a),u(d))c=me.m(c,pe(a),b),a=d,b=e;else return null;else return null;else return new X(null,2,5,ge,[d,c],null)}}else return null},re=function(a,b,c,d,e){return be(d,function(g,h,k){var l=sa(g);c.m?c.m(l,h,k):c.call(null,l,h,k);E(h," ");g=ua(g);return c.m?c.m(g,h,k):c.call(null,g,h,k)},[y.g(a),"{"].join(""),", ","}",e,I(b))},je=function(a,b,c,d){var e=Rb(a)?qe(a):null,g=Ib(e,0,null);e=Ib(e,1,null);return u(g)?re(["#:",y.g(g)].join(""),e,b,c,d):re(null,a,b,c,d)},se=function(a){a=
null!=a?a.grants:null;return new Set(u(a)?a:[])},te=function(a,b){var c=Error("kototama.tender: host import denied");a=Object.assign({"import":"cap-call",reason:a},b);c.kototamaDenied=a;throw c;},ue=function(a){var b=se(a);return{call:function(c){c="number"===typeof c?BigInt(c):c;return R.h(y.g(c),"7")?u(b.has("clock-monotonic"))?BigInt(Date.now()):te("grant/missing",{grant:"clock-monotonic","capability-id":Number(c)}):te("grant/unknown-capability",{"capability-id":Number(c)})}}};/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var ve="closure_uid_"+(1E9*Math.random()>>>0),we=0;f=ba.prototype;f.Ba="";f.set=function(a){this.Ba=""+a};f.append=function(a,b,c){this.Ba+=String(a);if(null!=b)for(let d=1;d<arguments.length;d++)this.Ba+=arguments[d];return this};f.clear=function(){this.Ba=""};f.toString=function(){return this.Ba};var G={},$d=null,ob="undefined"!==typeof Symbol&&"function"===t(Symbol)?Symbol.iterator:"@@iterator",xe=function(){function a(d,e,g){var h=U[t(null==d?null:d)];if(null!=h)return h.m?h.m(d,e,g):h.call(null,d,e,g);h=U._;if(null!=h)return h.m?h.m(d,e,g):h.call(null,d,e,g);throw x("IIndexed.-nth",d);}function b(d,e){var g=U[t(null==d?null:d)];if(null!=g)return g.h?g.h(d,e):g.call(null,d,e);g=U._;if(null!=g)return g.h?g.h(d,e):g.call(null,d,e);throw x("IIndexed.-nth",d);}var c=null;c=function(d,e,g){switch(arguments.length){case 2:return b.call(this,
d,e);case 3:return a.call(this,d,e,g)}throw Error("Invalid arity: "+arguments.length);};c.h=b;c.m=a;return c}(),U=function U(a){switch(arguments.length){case 2:return U.h(arguments[0],arguments[1]);case 3:return U.m(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",y.g(arguments.length)].join(""));}};U.h=function(a,b){return null!=a&&null!=a.ea?a.ea(a,b):xe(a,b)};U.m=function(a,b,c){return null!=a&&null!=a.la?a.la(a,b,c):xe(a,b,c)};U.ga=3;
var ye=function(){function a(d,e,g){var h=Mb[t(null==d?null:d)];if(null!=h)return h.m?h.m(d,e,g):h.call(null,d,e,g);h=Mb._;if(null!=h)return h.m?h.m(d,e,g):h.call(null,d,e,g);throw x("ILookup.-lookup",d);}function b(d,e){var g=Mb[t(null==d?null:d)];if(null!=g)return g.h?g.h(d,e):g.call(null,d,e);g=Mb._;if(null!=g)return g.h?g.h(d,e):g.call(null,d,e);throw x("ILookup.-lookup",d);}var c=null;c=function(d,e,g){switch(arguments.length){case 2:return b.call(this,d,e);case 3:return a.call(this,d,e,g)}throw Error("Invalid arity: "+
arguments.length);};c.h=b;c.m=a;return c}(),Mb=function Mb(a){switch(arguments.length){case 2:return Mb.h(arguments[0],arguments[1]);case 3:return Mb.m(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",y.g(arguments.length)].join(""));}};Mb.h=function(a,b){return null!=a&&null!=a.ka?a.ka(a,b):ye(a,b)};Mb.m=function(a,b,c){return null!=a&&null!=a.H?a.H(a,b,c):ye(a,b,c)};Mb.ga=3;
var ze=function(){function a(d,e,g){var h=ec[t(null==d?null:d)];if(null!=h)return h.m?h.m(d,e,g):h.call(null,d,e,g);h=ec._;if(null!=h)return h.m?h.m(d,e,g):h.call(null,d,e,g);throw x("IReduce.-reduce",d);}function b(d,e){var g=ec[t(null==d?null:d)];if(null!=g)return g.h?g.h(d,e):g.call(null,d,e);g=ec._;if(null!=g)return g.h?g.h(d,e):g.call(null,d,e);throw x("IReduce.-reduce",d);}var c=null;c=function(d,e,g){switch(arguments.length){case 2:return b.call(this,d,e);case 3:return a.call(this,d,e,g)}throw Error("Invalid arity: "+
arguments.length);};c.h=b;c.m=a;return c}(),ec=function ec(a){switch(arguments.length){case 2:return ec.h(arguments[0],arguments[1]);case 3:return ec.m(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",y.g(arguments.length)].join(""));}};ec.h=function(a,b){return null!=a&&null!=a.Z?a.Z(a,b):ze(a,b)};ec.m=function(a,b,c){return null!=a&&null!=a.$?a.$(a,b,c):ze(a,b,c)};ec.ga=3;Va.prototype.vb=function(a,b){return this.Mb.append(b)};
var cb="undefined"!==typeof Math&&"undefined"!==typeof Math.imul?function(a,b){return Math.imul(a,b)}:function(a,b){var c=a&65535,d=b&65535;return c*d+((a>>>16&65535)*d+c*(b>>>16&65535)<<16>>>0)|0},ib={},hb=0;f=mb.prototype;f.toString=function(){return this.Aa};f.J=function(a,b){return b instanceof mb?this.Aa===b.Aa:!1};
f.call=function(a){switch(arguments.length-1){case 1:return this.g(arguments[1]);case 2:return this.h(arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",y.g(arguments.length-1)].join(""));}};f.apply=function(a,b){return this.call.apply(this,[this].concat(z(b)))};f.g=function(a){return Jb?Jb(a,this):Lb.call(null,a,this)};f.h=function(a,b){return Kb?Kb(a,this,b):Lb.call(null,a,this,b)};f.O=function(){return this.ra};f.P=function(a,b){return new mb(this.eb,this.name,this.Aa,this.Ta,b)};
f.N=function(){var a=this.Ta;return null!=a?a:this.Ta=a=lb(gb(this.name),jb(this.eb))};f.K=function(a,b){return E(b,this.Aa)};var oe=function oe(a){switch(arguments.length){case 1:return oe.g(arguments[0]);case 2:return oe.h(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",y.g(arguments.length)].join(""));}};
oe.g=function(a){for(;;){if(a instanceof mb)return a;if("string"===typeof a){var b=a.indexOf("/");return 1>b?oe.h(null,a):oe.h(a.substring(0,b),a.substring(b+1,a.length))}if(a instanceof W)a=a.va;else throw Error("no conversion to symbol");}};oe.h=function(a,b){var c=null!=a?[y.g(a),"/",y.g(b)].join(""):b;return new mb(a,b,c,null,null)};oe.ga=2;
var R=function R(a){switch(arguments.length){case 1:return R.g(arguments[0]);case 2:return R.h(arguments[0],arguments[1]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return R.S(arguments[0],arguments[1],2<c.length?new H(c.slice(2),0,null):null)}};R.g=function(){return!0};R.h=function(a,b){return null==a?null==b:a===b||Da(a,b)};R.S=function(a,b,c){for(;;)if(R.h(a,b))if(N(c))a=b,b=J(c),c=N(c);else return R.h(b,J(c));else return!1};
R.ba=function(a){var b=J(a),c=N(a);a=J(c);c=N(c);return this.S(b,a,c)};R.ga=2;rb.prototype.next=function(){if(null!=this.C){var a=J(this.C);this.C=N(this.C);return{value:a,done:!1}}return{value:null,done:!0}};sb.prototype.I=function(){return this};sb.prototype.aa=function(){return this.value};sb.prototype.fa=function(){null==this.jb&&(this.jb=pb.g?pb.g(this.wb):pb.call(null,this.wb));return this.jb};var Ae=fb(eb(0,db(1)),0),Be=fb(eb(0,db(0)),0);fa["null"]=!0;ha["null"]=function(){return 0};
Date.prototype.J=function(a,b){return b instanceof Date&&this.valueOf()===b.valueOf()};Da.number=function(a,b){return a===b};xa["function"]=!0;ya["function"]=function(){return null};Ea._=function(a){return Object.prototype.hasOwnProperty.call(a,ve)&&a[ve]||(a[ve]=++we)};vb.prototype.Ab=function(){return this.G};Fb.prototype.ia=function(){return this.o<this.i.length};Fb.prototype.next=function(){var a=this.i[this.o];this.o+=1;return a};f=H.prototype;f.toString=function(){return bb(this)};
f.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return S(this,b,0);case 2:return S(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.g=function(b){return S(this,b,0)};a.h=function(b,c){return S(this,b,c)};return a}();
f.lastIndexOf=function(){function a(c){return T(this,c,Q.g?Q.g(this):Q.call(null,this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return T(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.g=a;b.h=function(c,d){return T(this,c,d)};return b}();f.ea=function(a,b){a=b+this.o;if(0<=a&&a<this.i.length)return this.i[a];throw Error("Index out of bounds");};f.la=function(a,b,c){a=b+this.o;return 0<=a&&a<this.i.length?this.i[a]:c};
f.sa=function(){return new Fb(this.i,this.o)};f.O=function(){return this.u};f.X=function(){return this.o+1<this.i.length?new H(this.i,this.o+1,null):null};f.U=function(){var a=this.i.length-this.o;return 0>a?0:a};f.N=function(){return tb(this)};f.J=function(a,b){return jc.h?jc.h(this,b):jc.call(null,this,b)};f.V=function(){return M};f.Z=function(a,b){return Ab(this.i,b,this.i[this.o],this.o+1)};f.$=function(a,b,c){return Ab(this.i,b,c,this.o)};f.aa=function(){return this.i[this.o]};
f.fa=function(){return this.o+1<this.i.length?new H(this.i,this.o+1,null):M};f.I=function(){return this.o<this.i.length?this:null};f.P=function(a,b){return b===this.u?this:new H(this.i,this.o,b)};f.T=function(a,b){return V.h?V.h(b,this):V.call(null,b,this)};H.prototype[ob]=function(){return O(this)};Da._=function(a,b){return a===b};
var Ic=function Ic(a){switch(arguments.length){case 0:return Ic.F();case 1:return Ic.g(arguments[0]);case 2:return Ic.h(arguments[0],arguments[1]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return Ic.S(arguments[0],arguments[1],2<c.length?new H(c.slice(2),0,null):null)}};Ic.F=function(){return he};Ic.g=function(a){return a};Ic.h=function(a,b){return null!=a?ka(a,b):new kc(null,b,null,1,null)};
Ic.S=function(a,b,c){for(;;)if(u(c))a=Ic.h(a,b),b=J(c),c=N(c);else return Ic.h(a,b)};Ic.ba=function(a){var b=J(a),c=N(a);a=J(c);c=N(c);return this.S(b,a,c)};Ic.ga=2;var me=function me(a){switch(arguments.length){case 3:return me.m(arguments[0],arguments[1],arguments[2]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return me.S(arguments[0],arguments[1],arguments[2],3<c.length?new H(c.slice(3),0,null):null)}};
me.m=function(a,b,c){if(null!=a&&(a.j&512||G===a.yb))a=a.xa(null,b,c);else if(null!=a)a=qa(a,b,c);else{a=[b,c];b=a.length;c=1===(b&1);var d;if(!(d=c))a:for(d=0;;)if(d<a.length){var e;b:for(e=0;;)if(e<d){var g=kd(a[d],a[e]);if(g){e=g;break b}e=2+e}else{e=!1;break b}if(e){d=e;break a}d=2+d}else{d=!1;break a}a=d?od(a,c):new Wa(null,b/2,a,null)}return a};me.S=function(a,b,c,d){for(;;)if(a=me.m(a,b,c),u(d))b=J(d),c=J(N(d)),d=N(N(d));else return a};
me.ba=function(a){var b=J(a),c=N(a);a=J(c);var d=N(c);c=J(d);d=N(d);return this.S(b,a,c,d)};me.ga=3;f=Nb.prototype;f.O=function(){return this.u};f.P=function(a,b){return new Nb(this.s,b)};
f.call=function(a){switch(arguments.length-1){case 0:return this.F();case 1:return this.g(arguments[1]);case 2:return this.h(arguments[1],arguments[2]);case 3:return this.m(arguments[1],arguments[2],arguments[3]);case 4:return this.W(arguments[1],arguments[2],arguments[3],arguments[4]);case 5:return this.ua(arguments[1],arguments[2],arguments[3],arguments[4],arguments[5]);case 6:return this.Na(arguments[1],arguments[2],arguments[3],arguments[4],arguments[5],arguments[6]);case 7:return this.Oa(arguments[1],
arguments[2],arguments[3],arguments[4],arguments[5],arguments[6],arguments[7]);case 8:return this.Pa(arguments[1],arguments[2],arguments[3],arguments[4],arguments[5],arguments[6],arguments[7],arguments[8]);case 9:return this.Qa(arguments[1],arguments[2],arguments[3],arguments[4],arguments[5],arguments[6],arguments[7],arguments[8],arguments[9]);case 10:return this.Ca(arguments[1],arguments[2],arguments[3],arguments[4],arguments[5],arguments[6],arguments[7],arguments[8],arguments[9],arguments[10]);
case 11:return this.Da(arguments[1],arguments[2],arguments[3],arguments[4],arguments[5],arguments[6],arguments[7],arguments[8],arguments[9],arguments[10],arguments[11]);case 12:return this.Ea(arguments[1],arguments[2],arguments[3],arguments[4],arguments[5],arguments[6],arguments[7],arguments[8],arguments[9],arguments[10],arguments[11],arguments[12]);case 13:return this.Fa(arguments[1],arguments[2],arguments[3],arguments[4],arguments[5],arguments[6],arguments[7],arguments[8],arguments[9],arguments[10],
arguments[11],arguments[12],arguments[13]);case 14:return this.Ga(arguments[1],arguments[2],arguments[3],arguments[4],arguments[5],arguments[6],arguments[7],arguments[8],arguments[9],arguments[10],arguments[11],arguments[12],arguments[13],arguments[14]);case 15:return this.Ha(arguments[1],arguments[2],arguments[3],arguments[4],arguments[5],arguments[6],arguments[7],arguments[8],arguments[9],arguments[10],arguments[11],arguments[12],arguments[13],arguments[14],arguments[15]);case 16:return this.Ia(arguments[1],
arguments[2],arguments[3],arguments[4],arguments[5],arguments[6],arguments[7],arguments[8],arguments[9],arguments[10],arguments[11],arguments[12],arguments[13],arguments[14],arguments[15],arguments[16]);case 17:return this.Ja(arguments[1],arguments[2],arguments[3],arguments[4],arguments[5],arguments[6],arguments[7],arguments[8],arguments[9],arguments[10],arguments[11],arguments[12],arguments[13],arguments[14],arguments[15],arguments[16],arguments[17]);case 18:return this.Ka(arguments[1],arguments[2],
arguments[3],arguments[4],arguments[5],arguments[6],arguments[7],arguments[8],arguments[9],arguments[10],arguments[11],arguments[12],arguments[13],arguments[14],arguments[15],arguments[16],arguments[17],arguments[18]);case 19:return this.La(arguments[1],arguments[2],arguments[3],arguments[4],arguments[5],arguments[6],arguments[7],arguments[8],arguments[9],arguments[10],arguments[11],arguments[12],arguments[13],arguments[14],arguments[15],arguments[16],arguments[17],arguments[18],arguments[19]);case 20:return this.Ma(arguments[1],
arguments[2],arguments[3],arguments[4],arguments[5],arguments[6],arguments[7],arguments[8],arguments[9],arguments[10],arguments[11],arguments[12],arguments[13],arguments[14],arguments[15],arguments[16],arguments[17],arguments[18],arguments[19],arguments[20]);case 21:return this.nb(arguments[1],arguments[2],arguments[3],arguments[4],arguments[5],arguments[6],arguments[7],arguments[8],arguments[9],arguments[10],arguments[11],arguments[12],arguments[13],arguments[14],arguments[15],arguments[16],arguments[17],
arguments[18],arguments[19],arguments[20],arguments[21]);default:throw Error(["Invalid arity: ",y.g(arguments.length-1)].join(""));}};f.apply=function(a,b){return this.call.apply(this,[this].concat(z(b)))};f.F=function(){return this.s.F?this.s.F():this.s.call(null)};f.g=function(a){return this.s.g?this.s.g(a):this.s.call(null,a)};f.h=function(a,b){return this.s.h?this.s.h(a,b):this.s.call(null,a,b)};f.m=function(a,b,c){return this.s.m?this.s.m(a,b,c):this.s.call(null,a,b,c)};
f.W=function(a,b,c,d){return this.s.W?this.s.W(a,b,c,d):this.s.call(null,a,b,c,d)};f.ua=function(a,b,c,d,e){return this.s.ua?this.s.ua(a,b,c,d,e):this.s.call(null,a,b,c,d,e)};f.Na=function(a,b,c,d,e,g){return this.s.Na?this.s.Na(a,b,c,d,e,g):this.s.call(null,a,b,c,d,e,g)};f.Oa=function(a,b,c,d,e,g,h){return this.s.Oa?this.s.Oa(a,b,c,d,e,g,h):this.s.call(null,a,b,c,d,e,g,h)};f.Pa=function(a,b,c,d,e,g,h,k){return this.s.Pa?this.s.Pa(a,b,c,d,e,g,h,k):this.s.call(null,a,b,c,d,e,g,h,k)};
f.Qa=function(a,b,c,d,e,g,h,k,l){return this.s.Qa?this.s.Qa(a,b,c,d,e,g,h,k,l):this.s.call(null,a,b,c,d,e,g,h,k,l)};f.Ca=function(a,b,c,d,e,g,h,k,l,m){return this.s.Ca?this.s.Ca(a,b,c,d,e,g,h,k,l,m):this.s.call(null,a,b,c,d,e,g,h,k,l,m)};f.Da=function(a,b,c,d,e,g,h,k,l,m,n){return this.s.Da?this.s.Da(a,b,c,d,e,g,h,k,l,m,n):this.s.call(null,a,b,c,d,e,g,h,k,l,m,n)};f.Ea=function(a,b,c,d,e,g,h,k,l,m,n,p){return this.s.Ea?this.s.Ea(a,b,c,d,e,g,h,k,l,m,n,p):this.s.call(null,a,b,c,d,e,g,h,k,l,m,n,p)};
f.Fa=function(a,b,c,d,e,g,h,k,l,m,n,p,q){return this.s.Fa?this.s.Fa(a,b,c,d,e,g,h,k,l,m,n,p,q):this.s.call(null,a,b,c,d,e,g,h,k,l,m,n,p,q)};f.Ga=function(a,b,c,d,e,g,h,k,l,m,n,p,q,r){return this.s.Ga?this.s.Ga(a,b,c,d,e,g,h,k,l,m,n,p,q,r):this.s.call(null,a,b,c,d,e,g,h,k,l,m,n,p,q,r)};f.Ha=function(a,b,c,d,e,g,h,k,l,m,n,p,q,r,w){return this.s.Ha?this.s.Ha(a,b,c,d,e,g,h,k,l,m,n,p,q,r,w):this.s.call(null,a,b,c,d,e,g,h,k,l,m,n,p,q,r,w)};
f.Ia=function(a,b,c,d,e,g,h,k,l,m,n,p,q,r,w,A){return this.s.Ia?this.s.Ia(a,b,c,d,e,g,h,k,l,m,n,p,q,r,w,A):this.s.call(null,a,b,c,d,e,g,h,k,l,m,n,p,q,r,w,A)};f.Ja=function(a,b,c,d,e,g,h,k,l,m,n,p,q,r,w,A,B){return this.s.Ja?this.s.Ja(a,b,c,d,e,g,h,k,l,m,n,p,q,r,w,A,B):this.s.call(null,a,b,c,d,e,g,h,k,l,m,n,p,q,r,w,A,B)};f.Ka=function(a,b,c,d,e,g,h,k,l,m,n,p,q,r,w,A,B,F){return this.s.Ka?this.s.Ka(a,b,c,d,e,g,h,k,l,m,n,p,q,r,w,A,B,F):this.s.call(null,a,b,c,d,e,g,h,k,l,m,n,p,q,r,w,A,B,F)};
f.La=function(a,b,c,d,e,g,h,k,l,m,n,p,q,r,w,A,B,F,K){return this.s.La?this.s.La(a,b,c,d,e,g,h,k,l,m,n,p,q,r,w,A,B,F,K):this.s.call(null,a,b,c,d,e,g,h,k,l,m,n,p,q,r,w,A,B,F,K)};f.Ma=function(a,b,c,d,e,g,h,k,l,m,n,p,q,r,w,A,B,F,K,P){return this.s.Ma?this.s.Ma(a,b,c,d,e,g,h,k,l,m,n,p,q,r,w,A,B,F,K,P):this.s.call(null,a,b,c,d,e,g,h,k,l,m,n,p,q,r,w,A,B,F,K,P)};
f.nb=function(a,b,c,d,e,g,h,k,l,m,n,p,q,r,w,A,B,F,K,P,ca){return Fc.nb?Fc.nb(this.s,a,b,c,d,e,g,h,k,l,m,n,p,q,r,w,A,B,F,K,new H([P,ca],0,null)):Fc.call(null,this.s,a,b,c,d,e,g,h,k,l,m,n,p,q,r,w,A,B,F,K,P,ca)};var Xb={},y=function y(a){switch(arguments.length){case 0:return y.F();case 1:return y.g(arguments[0]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return y.S(arguments[0],1<c.length?new H(c.slice(1),0,null):null)}};y.F=function(){return""};
y.g=function(a){return null==a?"":[a].join("")};y.S=function(a,b){for(a=new ba(y.g(a));;)if(u(b))a=a.append(y.g(J(b))),b=N(b);else return a.toString()};y.ba=function(a){var b=J(a);a=N(a);return this.S(b,a)};y.ga=1;f=kc.prototype;f.toString=function(){return bb(this)};
f.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return S(this,b,0);case 2:return S(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.g=function(b){return S(this,b,0)};a.h=function(b,c){return S(this,b,c)};return a}();
f.lastIndexOf=function(){function a(c){return T(this,c,this.count)}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return T(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.g=a;b.h=function(c,d){return T(this,c,d)};return b}();f.O=function(){return this.u};f.X=function(){return 1===this.count?null:this.wa};f.U=function(){return this.count};f.N=function(){var a=this.v;return null!=a?a:this.v=a=tb(this)};f.J=function(a,b){return jc(this,b)};
f.V=function(){return za(M,this.u)};f.Z=function(a,b){return ac(b,this)};f.$=function(a,b,c){return bc(b,c,this)};f.aa=function(){return this.first};f.fa=function(){return 1===this.count?M:this.wa};f.I=function(){return this};f.P=function(a,b){return b===this.u?this:new kc(b,this.first,this.wa,this.count,this.v)};f.T=function(a,b){return new kc(this.u,b,this,this.count+1,null)};kc.prototype[ob]=function(){return O(this)};f=lc.prototype;f.toString=function(){return bb(this)};
f.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return S(this,b,0);case 2:return S(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.g=function(b){return S(this,b,0)};a.h=function(b,c){return S(this,b,c)};return a}();
f.lastIndexOf=function(){function a(c){return T(this,c,Q(this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return T(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.g=a;b.h=function(c,d){return T(this,c,d)};return b}();f.O=function(){return this.u};f.X=function(){return null};f.U=function(){return 0};f.N=function(){return Ae};f.J=function(a,b){return(null!=b?b.j&33554432||G===b.Sb||(b.j?0:v(Ia,b)):v(Ia,b))||Qb(b)?null==I(b):!1};f.V=function(){return this};
f.Z=function(a,b){return ac(b,this)};f.$=function(a,b,c){return bc(b,c,this)};f.aa=function(){return null};f.fa=function(){return M};f.I=function(){return null};f.P=function(a,b){return b===this.u?this:new lc(b)};f.T=function(a,b){return new kc(this.u,b,null,1,null)};var M=new lc(null);lc.prototype[ob]=function(){return O(this)};f=mc.prototype;f.toString=function(){return bb(this)};
f.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return S(this,b,0);case 2:return S(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.g=function(b){return S(this,b,0)};a.h=function(b,c){return S(this,b,c)};return a}();
f.lastIndexOf=function(){function a(c){return T(this,c,Q(this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return T(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.g=a;b.h=function(c,d){return T(this,c,d)};return b}();f.O=function(){return this.u};f.X=function(){return null==this.wa?null:I(this.wa)};f.N=function(){var a=this.v;return null!=a?a:this.v=a=tb(this)};f.J=function(a,b){return jc(this,b)};f.V=function(){return M};
f.Z=function(a,b){return ac(b,this)};f.$=function(a,b,c){return bc(b,c,this)};f.aa=function(){return this.first};f.fa=function(){return null==this.wa?M:this.wa};f.I=function(){return this};f.P=function(a,b){return b===this.u?this:new mc(b,this.first,this.wa,this.v)};f.T=function(a,b){return new mc(null,b,this,null)};mc.prototype[ob]=function(){return O(this)};f=W.prototype;f.toString=function(){return[":",y.g(this.va)].join("")};f.J=function(a,b){return b instanceof W?this.va===b.va:!1};
f.call=function(a){switch(arguments.length-1){case 1:return this.g(arguments[1]);case 2:return this.h(arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",y.g(arguments.length-1)].join(""));}};f.apply=function(a,b){return this.call.apply(this,[this].concat(z(b)))};f.g=function(a){return Jb(a,this)};f.h=function(a,b){return Kb(a,this,b)};f.N=function(){var a=this.Ta;return null!=a?a:this.Ta=a=lb(gb(this.name),jb(this.eb))+2654435769|0};f.K=function(a,b){return E(b,[":",y.g(this.va)].join(""))};
var ie=function ie(a){switch(arguments.length){case 1:return ie.g(arguments[0]);case 2:return ie.h(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",y.g(arguments.length)].join(""));}};ie.g=function(a){if(a instanceof W)return a;if(a instanceof mb)return new W(nc(a),Zd.g?Zd.g(a):Zd.call(null,a),a.Aa,null);if(R.h("/",a))return new W(null,a,a,null);if("string"===typeof a){var b=a.split("/");return 2===b.length?new W(b[0],b[1],a,null):new W(null,b[0],a,null)}return null};
ie.h=function(a,b){a=a instanceof W?Zd.g?Zd.g(a):Zd.call(null,a):a instanceof mb?Zd.g?Zd.g(a):Zd.call(null,a):a;b=b instanceof W?Zd.g?Zd.g(b):Zd.call(null,b):b instanceof mb?Zd.g?Zd.g(b):Zd.call(null,b):b;return new W(a,b,[u(a)?[y.g(a),"/"].join(""):null,y.g(b)].join(""),null)};ie.ga=2;f=oc.prototype;f.toString=function(){return bb(this)};
f.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return S(this,b,0);case 2:return S(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.g=function(b){return S(this,b,0)};a.h=function(b,c){return S(this,b,c)};return a}();
f.lastIndexOf=function(){function a(c){return T(this,c,Q(this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return T(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.g=a;b.h=function(c,d){return T(this,c,d)};return b}();f.O=function(){return this.u};f.X=function(){this.I(null);return null==this.C?null:N(this.C)};f.N=function(){var a=this.v;return null!=a?a:this.v=a=tb(this)};f.J=function(a,b){return jc(this,b)};f.V=function(){return za(M,this.u)};
f.Z=function(a,b){return ac(b,this)};f.$=function(a,b,c){return bc(b,c,this)};f.aa=function(){this.I(null);return null==this.C?null:J(this.C)};f.fa=function(){this.I(null);return null!=this.C?qb(this.C):M};f.I=function(){pc(this);if(null==this.C)return null;for(var a=this.C;;)if(a instanceof oc)a=pc(a);else return this.C=a,I(this.C)};f.P=function(a,b){var c=this;return b===this.u?c:new oc(b,function(){return c.I(null)},this.v)};f.T=function(a,b){return V(b,this)};oc.prototype[ob]=function(){return O(this)};
qc.prototype.add=function(a){this.lb[this.end]=a;return this.end+=1};qc.prototype.ta=function(){var a=new rc(this.lb,0,this.end);this.lb=null;return a};qc.prototype.U=function(){return this.end};f=rc.prototype;f.U=function(){return this.end-this.R};f.ea=function(a,b){return this.i[this.R+b]};f.la=function(a,b,c){return 0<=b&&b<this.end-this.R?this.i[this.R+b]:c};f.rb=function(){if(this.R===this.end)throw Error("-drop-first of empty chunk");return new rc(this.i,this.R+1,this.end)};
f.Z=function(a,b){return Ab(this.i,b,this.i[this.R],this.R+1)};f.$=function(a,b,c){return Ab(this.i,b,c,this.R)};f=sc.prototype;f.toString=function(){return bb(this)};f.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return S(this,b,0);case 2:return S(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.g=function(b){return S(this,b,0)};a.h=function(b,c){return S(this,b,c)};return a}();
f.lastIndexOf=function(){function a(c){return T(this,c,Q(this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return T(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.g=a;b.h=function(c,d){return T(this,c,d)};return b}();f.O=function(){return this.u};f.X=function(){return 1<ha(this.ta)?new sc(Qa(this.ta),this.oa,null,null):null==this.oa?null:Ga(this.oa)};f.N=function(){var a=this.v;return null!=a?a:this.v=a=tb(this)};
f.J=function(a,b){return jc(this,b)};f.V=function(){return M};f.aa=function(){return U(this.ta,0)};f.fa=function(){return 1<ha(this.ta)?new sc(Qa(this.ta),this.oa,null,null):null==this.oa?M:this.oa};f.I=function(){return this};f.mb=function(){return this.ta};f.fb=function(){return null==this.oa?M:this.oa};f.P=function(a,b){return b===this.u?this:new sc(this.ta,this.oa,b,this.v)};f.T=function(a,b){return V(b,this)};f.sb=function(){return null==this.oa?null:this.oa};sc.prototype[ob]=function(){return O(this)};
var Ec=function Ec(a){if(null==a)return null;var c=N(a);return null==c?I(J(a)):V(J(a),Ec.g?Ec.g(c):Ec.call(null,c))};f=Gc.prototype;f.P=function(a,b){return new Gc(b)};f.O=function(){return this.Lb};f.ia=function(){return!1};f.next=function(){return Error("No such element")};f.remove=function(){return Error("Unsupported operation")};
var Z=function Z(a){switch(arguments.length){case 1:return Z.g(arguments[0]);case 2:return Z.h(arguments[0],arguments[1]);case 3:return Z.m(arguments[0],arguments[1],arguments[2]);case 4:return Z.W(arguments[0],arguments[1],arguments[2],arguments[3]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return Z.S(arguments[0],arguments[1],arguments[2],arguments[3],4<c.length?new H(c.slice(4),0,null):null)}};
Z.g=function(a){return function(b){return function(){function c(k,l){l=a.g?a.g(l):a.call(null,l);return b.h?b.h(k,l):b.call(null,k,l)}function d(k){return b.g?b.g(k):b.call(null,k)}function e(){return b.F?b.F():b.call(null)}var g=null,h=function(){function k(m,n,p){var q=null;if(2<arguments.length){q=0;for(var r=Array(arguments.length-2);q<r.length;)r[q]=arguments[q+2],++q;q=new H(r,0,null)}return l.call(this,m,n,q)}function l(m,n,p){n=Dc(a,n,p);return b.h?b.h(m,n):b.call(null,m,n)}k.ga=2;k.ba=function(m){var n=
J(m);m=N(m);var p=J(m);m=qb(m);return l(n,p,m)};k.S=l;return k}();g=function(k,l,m){switch(arguments.length){case 0:return e.call(this);case 1:return d.call(this,k);case 2:return c.call(this,k,l);default:var n=null;if(2<arguments.length){n=0;for(var p=Array(arguments.length-2);n<p.length;)p[n]=arguments[n+2],++n;n=new H(p,0,null)}return h.S(k,l,n)}throw Error("Invalid arity: "+arguments.length);};g.ga=2;g.ba=h.ba;g.F=e;g.g=d;g.h=c;g.S=h.S;return g}()}};
Z.h=function(a,b){return new oc(null,function(){var c=I(b);if(c){if(Ub(c)){for(var d=Ra(c),e=Q(d),g=new qc(Array(e)),h=0;;)if(h<e)uc(g,function(){var k=U(d,h);return a.g?a.g(k):a.call(null,k)}()),h+=1;else break;return tc(g.ta(),Z.h(a,Sa(c)))}return V(function(){var k=J(c);return a.g?a.g(k):a.call(null,k)}(),Z.h(a,qb(c)))}return null},null)};
Z.m=function(a,b,c){return new oc(null,function(){var d=I(b),e=I(c);if(d&&e){var g=J(d);var h=J(e);g=a.h?a.h(g,h):a.call(null,g,h);d=V(g,Z.m(a,qb(d),qb(e)))}else d=null;return d},null)};Z.W=function(a,b,c,d){return new oc(null,function(){var e=I(b),g=I(c),h=I(d);if(e&&g&&h){var k=J(e);var l=J(g),m=J(h);k=a.m?a.m(k,l,m):a.call(null,k,l,m);e=V(k,Z.W(a,qb(e),qb(g),qb(h)))}else e=null;return e},null)};
Z.S=function(a,b,c,d,e){return Z.h(function(g){return Cc(a,g)},function k(h){return new oc(null,function(){var l=Z.h(I,h);return Hc(gc,l)?V(Z.h(J,l),k(Z.h(qb,l))):null},null)}(Ic.S(e,d,Gb([c,b]))))};Z.ba=function(a){var b=J(a),c=N(a);a=J(c);var d=N(c);c=J(d);var e=N(d);d=J(e);e=N(e);return this.S(b,a,c,d,e)};Z.ga=4;
var Ce=function Ce(a,b,c,d){var g=new Kc(c.D,z(c.i)),h=a.l-1>>>b&31;5===b?g.i[h]=d:(c=c.i[h],null!=c?(b-=5,a=Ce.W?Ce.W(a,b,c,d):Ce.call(null,a,b,c,d)):a=Nc(null,b-5,d),g.i[h]=a);return g},De=function De(a,b,c,d,e){var h=new Kc(c.D,z(c.i));if(0===b)h.i[d&31]=e;else{var k=d>>>b&31;b-=5;c=c.i[k];a=De.ua?De.ua(a,b,c,d,e):De.call(null,a,b,c,d,e);h.i[k]=a}return h};Qc.prototype.ia=function(){return this.o<this.end};
Qc.prototype.next=function(){32===this.o-this.kb&&(this.i=Oc(this.Nb,this.o),this.kb+=32);var a=this.i[this.o&31];this.o+=1;return a};f=X.prototype;f.toString=function(){return bb(this)};f.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return S(this,b,0);case 2:return S(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.g=function(b){return S(this,b,0)};a.h=function(b,c){return S(this,b,c)};return a}();
f.lastIndexOf=function(){function a(c){return T(this,c,Q(this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return T(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.g=a;b.h=function(c,d){return T(this,c,d)};return b}();f.ka=function(a,b){return this.H(null,b,null)};f.H=function(a,b,c){return"number"===typeof b?this.la(null,b,c):c};
f.gb=function(a,b,c){a=0;for(var d=c;;)if(a<this.l){var e=Oc(this,a);c=e.length;a:for(var g=0;;)if(g<c){var h=g+a,k=e[g];d=b.m?b.m(d,h,k):b.call(null,d,h,k);if(wb(d)){e=d;break a}g+=1}else{e=d;break a}if(wb(e))return wa(e);a+=c;d=e}else return d};f.ea=function(a,b){return Pc(this,b)[b&31]};f.la=function(a,b,c){return 0<=b&&b<this.l?Oc(this,b)[b&31]:c};
f.ob=function(a,b){if(0<=a&&a<this.l){if(Mc(this)<=a){var c=z(this.da);c[a&31]=b;return new X(this.u,this.l,this.shift,this.root,c,null)}return new X(this.u,this.l,this.shift,De(this,this.shift,this.root,a,b),this.da,null)}if(a===this.l)return this.T(null,b);throw Error(["Index ",y.g(a)," out of bounds  [0,",y.g(this.l),"]"].join(""));};f.sa=function(){var a=this.l;return new Qc(0<Q(this)?Oc(this,0):null,this,a)};f.O=function(){return this.u};f.U=function(){return this.l};
f.N=function(){var a=this.v;return null!=a?a:this.v=a=tb(this)};f.J=function(a,b){if(b instanceof X)if(this.l===Q(b))for(a=this.sa(null),b=b.sa(null);;)if(a.ia()){var c=a.next(),d=b.next();if(!R.h(c,d))return!1}else return!0;else return!1;else return jc(this,b)};f.Xa=function(){return new $c(this.l,this.shift,Yc.g?Yc.g(this.root):Yc.call(null,this.root),Zc.g?Zc.g(this.da):Zc.call(null,this.da))};f.V=function(){return za(he,this.u)};f.Z=function(a,b){return Sc(this,b,0,this.l)};
f.$=function(a,b,c){a=0;for(var d=c;;)if(a<this.l){var e=Oc(this,a);c=e.length;a:for(var g=0;;)if(g<c){var h=e[g];d=b.h?b.h(d,h):b.call(null,d,h);if(wb(d)){e=d;break a}g+=1}else{e=d;break a}if(wb(e))return wa(e);a+=c;d=e}else return d};f.xa=function(a,b,c){if("number"===typeof b)return this.ob(b,c);throw Error("Vector's key for assoc must be a number.");};f.Ua=function(a,b){return"number"!==typeof b||isNaN(b)||Infinity===b||parseFloat(b)!==parseInt(b,10)?!1:0<=b&&b<this.l};
f.I=function(){if(0===this.l)return null;if(32>=this.l)return new H(this.da,0,null);a:{var a=this.root;for(var b=this.shift;;)if(0<b)b-=5,a=a.i[0];else{a=a.i;break a}}return Uc?Uc(this,a,0,0):Wc.call(null,this,a,0,0)};f.P=function(a,b){return b===this.u?this:new X(b,this.l,this.shift,this.root,this.da,this.v)};
f.T=function(a,b){if(32>this.l-Mc(this)){a=this.da.length;for(var c=Array(a+1),d=0;;)if(d<a)c[d]=this.da[d],d+=1;else break;c[a]=b;return new X(this.u,this.l+1,this.shift,this.root,c,null)}a=(c=this.l>>>5>1<<this.shift)?this.shift+5:this.shift;c?(c=Lc(null),c.i[0]=this.root,d=Nc(null,this.shift,new Kc(null,this.da)),c.i[1]=d):c=Ce(this,this.shift,this.root,new Kc(null,this.da));return new X(this.u,this.l+1,a,c,[b],null)};
f.call=function(a){switch(arguments.length-1){case 1:return this.g(arguments[1]);default:throw Error(["Invalid arity: ",y.g(arguments.length-1)].join(""));}};f.apply=function(a,b){return this.call.apply(this,[this].concat(z(b)))};f.g=function(a){if("number"===typeof a)return this.ea(null,a);throw Error("Key must be integer");};
var ge=new Kc(null,[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]),he=new X(null,0,5,ge,[],Ae);X.prototype[ob]=function(){return O(this)};f=Tc.prototype;f.toString=function(){return bb(this)};
f.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return S(this,b,0);case 2:return S(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.g=function(b){return S(this,b,0)};a.h=function(b,c){return S(this,b,c)};return a}();
f.lastIndexOf=function(){function a(c){return T(this,c,Q(this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return T(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.g=a;b.h=function(c,d){return T(this,c,d)};return b}();f.O=function(){return this.u};f.X=function(){if(this.R+1<this.node.length){var a=this.ja;var b=this.node,c=this.o,d=this.R+1;a=Uc?Uc(a,b,c,d):Wc.call(null,a,b,c,d);return null==a?null:a}return this.sb()};
f.N=function(){var a=this.v;return null!=a?a:this.v=a=tb(this)};f.J=function(a,b){return jc(this,b)};f.V=function(){return M};f.Z=function(a,b){return Sc(this.ja,b,this.o+this.R,Q(this.ja))};f.$=function(a,b,c){return Rc(this.ja,b,c,this.o+this.R,Q(this.ja))};f.aa=function(){return this.node[this.R]};f.fa=function(){if(this.R+1<this.node.length){var a=this.ja;var b=this.node,c=this.o,d=this.R+1;a=Uc?Uc(a,b,c,d):Wc.call(null,a,b,c,d);return null==a?M:a}return this.fb(null)};f.I=function(){return this};
f.mb=function(){var a=this.node;return new rc(a,this.R,a.length)};f.fb=function(){var a=this.o+this.node.length;if(a<ha(this.ja)){var b=this.ja,c=Oc(this.ja,a);return Uc?Uc(b,c,a,0):Wc.call(null,b,c,a,0)}return M};f.P=function(a,b){return b===this.u?this:Vc?Vc(this.ja,this.node,this.o,this.R,b):Wc.call(null,this.ja,this.node,this.o,this.R,b)};f.T=function(a,b){return V(b,this)};
f.sb=function(){var a=this.o+this.node.length;if(a<ha(this.ja)){var b=this.ja,c=Oc(this.ja,a);return Uc?Uc(b,c,a,0):Wc.call(null,b,c,a,0)}return null};Tc.prototype[ob]=function(){return O(this)};var Ee=function Ee(a,b,c,d){c=Xc(a.root.D,c);var g=a.l-1>>>b&31;if(5===b)a=d;else{var h=c.i[g];null!=h?(b-=5,a=Ee.W?Ee.W(a,b,h,d):Ee.call(null,a,b,h,d)):a=Nc(a.root.D,b-5,d)}c.i[g]=a;return c};f=$c.prototype;
f.Za=function(a,b){if(this.root.D){if(32>this.l-Mc(this))this.da[this.l&31]=b;else{a=new Kc(this.root.D,this.da);var c=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];c[0]=b;this.da=c;this.l>>>5>1<<this.shift?(b=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],c=this.shift+
5,b[0]=this.root,b[1]=Nc(this.root.D,this.shift,a),this.root=new Kc(this.root.D,b),this.shift=c):this.root=Ee(this,this.shift,this.root,a)}this.l+=1;return this}throw Error("conj! after persistent!");};f.ib=function(){if(this.root.D){this.root.D=null;var a=this.l-Mc(this),b=Array(a);Vb(this.da,0,b,0,a);return new X(null,this.l,this.shift,this.root,b,null)}throw Error("persistent! called twice");};
f.Va=function(a,b,c){if("number"===typeof b)return ad(this,b,c);throw Error("TransientVector's key for assoc! must be a number.");};f.U=function(){if(this.root.D)return this.l;throw Error("count after persistent!");};f.ea=function(a,b){if(this.root.D)return Pc(this,b)[b&31];throw Error("nth after persistent!");};f.la=function(a,b,c){return 0<=b&&b<this.l?this.ea(null,b):c};f.ka=function(a,b){return this.H(null,b,null)};
f.H=function(a,b,c){if(this.root.D)return"number"===typeof b?this.la(null,b,c):c;throw Error("lookup after persistent!");};f.call=function(a){switch(arguments.length-1){case 1:return this.g(arguments[1]);case 2:return this.h(arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",y.g(arguments.length-1)].join(""));}};f.apply=function(a,b){return this.call.apply(this,[this].concat(z(b)))};f.g=function(a){return this.ka(null,a)};f.h=function(a,b){return this.H(null,a,b)};bd.prototype.J=function(){return!1};
var cd=new bd;ed.prototype.next=function(){if(null!=this.C){var a=J(this.C),b=Ib(a,0,null);a=Ib(a,1,null);this.C=N(this.C);return{value:[b,a],done:!1}}return{value:null,done:!0}};f=gd.prototype;f.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return S(this,b,0);case 2:return S(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.g=function(b){return S(this,b,0)};a.h=function(b,c){return S(this,b,c)};return a}();
f.lastIndexOf=function(){function a(c){return T(this,c,Q(this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return T(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.g=a;b.h=function(c,d){return T(this,c,d)};return b}();f.ka=function(a,b){return this.la(null,b,null)};f.H=function(a,b,c){return this.la(null,b,c)};f.ea=function(a,b){if(0===b)return this.key;if(1===b)return this.G;throw Error("Index out of bounds");};
f.la=function(a,b,c){return 0===b?this.key:1===b?this.G:c};f.ob=function(a,b){return(new X(null,2,5,ge,[this.key,this.G],null)).ob(a,b)};f.O=function(){return null};f.U=function(){return 2};f.Eb=function(){return this.key};f.Fb=function(){return this.G};f.N=function(){var a=this.v;return null!=a?a:this.v=a=tb(this)};f.J=function(a,b){return jc(this,b)};f.V=function(){return null};
f.Z=function(a,b){a:if(a=this.U(null),0===a)b=b.F?b.F():b.call(null);else for(var c=this.ea(null,0),d=1;;)if(d<a){var e=this.ea(null,d);c=b.h?b.h(c,e):b.call(null,c,e);if(wb(c)){b=wa(c);break a}d+=1}else{b=c;break a}return b};f.$=function(a,b,c){a:{a=this.U(null);var d=c;for(c=0;;)if(c<a){var e=this.ea(null,c);d=b.h?b.h(d,e):b.call(null,d,e);if(wb(d)){b=wa(d);break a}c+=1}else{b=d;break a}}return b};f.xa=function(a,b,c){return me.m(new X(null,2,5,ge,[this.key,this.G],null),b,c)};
f.Ua=function(a,b){return 0===b||1===b};f.I=function(){return new H([this.key,this.G],0,null)};f.P=function(a,b){return Ob(new X(null,2,5,ge,[this.key,this.G],null),b)};f.T=function(a,b){return new X(null,3,5,ge,[this.key,this.G,b],null)};f.call=function(a){switch(arguments.length-1){case 1:return this.g(arguments[1]);case 2:return this.h(arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",y.g(arguments.length-1)].join(""));}};f.apply=function(a,b){return this.call.apply(this,[this].concat(z(b)))};
f.g=function(a){return this.ea(null,a)};f.h=function(a,b){return this.la(null,a,b)};f=id.prototype;f.toString=function(){return bb(this)};f.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return S(this,b,0);case 2:return S(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.g=function(b){return S(this,b,0)};a.h=function(b,c){return S(this,b,c)};return a}();
f.lastIndexOf=function(){function a(c){return T(this,c,Q(this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return T(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.g=a;b.h=function(c,d){return T(this,c,d)};return b}();f.O=function(){return this.ra};f.X=function(){return this.o<this.i.length-2?new id(this.i,this.o+2,null):null};f.U=function(){return(this.i.length-this.o)/2};f.N=function(){return tb(this)};f.J=function(a,b){return jc(this,b)};
f.V=function(){return M};f.Z=function(a,b){return ac(b,this)};f.$=function(a,b,c){return bc(b,c,this)};f.aa=function(){return new gd(this.i[this.o],this.i[this.o+1])};f.fa=function(){return this.o<this.i.length-2?new id(this.i,this.o+2,null):M};f.I=function(){return this};f.P=function(a,b){return b===this.ra?this:new id(this.i,this.o,b)};f.T=function(a,b){return V(b,this)};id.prototype[ob]=function(){return O(this)};jd.prototype.ia=function(){return this.o<this.l};
jd.prototype.next=function(){var a=new gd(this.i[this.o],this.i[this.o+1]);this.o+=2;return a};f=Wa.prototype;f.toString=function(){return bb(this)};f.keys=function(){return O(Ud.g?Ud.g(this):Ud.call(null,this))};f.entries=function(){return new ed(I(I(this)))};f.values=function(){return O(Xd.g?Xd.g(this):Xd.call(null,this))};f.has=function(a){return Yb(this,a)};f.get=function(a,b){return this.H(null,a,b)};
f.forEach=function(a){for(var b=I(this),c=null,d=0,e=0;;)if(e<d){var g=c.ea(null,e),h=Ib(g,0,null);g=Ib(g,1,null);a.h?a.h(g,h):a.call(null,g,h);e+=1}else if(b=I(b))Ub(b)?(c=Ra(b),b=Sa(b),h=c,d=Q(c),c=h):(c=J(b),h=Ib(c,0,null),g=Ib(c,1,null),a.h?a.h(g,h):a.call(null,g,h),b=N(b),c=null,d=0),e=0;else return null};f.ka=function(a,b){return this.H(null,b,null)};f.H=function(a,b,c){a=fd(this.i,b);return-1===a?c:this.i[a+1]};
f.gb=function(a,b,c){a=this.i.length;for(var d=0;;)if(d<a){var e=this.i[d],g=this.i[d+1];c=b.m?b.m(c,e,g):b.call(null,c,e,g);if(wb(c))return wa(c);d+=2}else return c};f.sa=function(){return new jd(this.i,2*this.l)};f.O=function(){return this.u};f.U=function(){return this.l};f.N=function(){var a=this.v;return null!=a?a:this.v=a=ub(this)};
f.J=function(a,b){if(Rb(b)&&!Sb(b))if(a=this.i.length,this.l===b.U(null))for(var c=0;;)if(c<a){var d=b.H(null,this.i[c],Xb);if(d!==Xb)if(R.h(this.i[c+1],d))c+=2;else return!1;else return!1}else return!0;else return!1;else return!1};f.Xa=function(){return new pd(this.i.length,z(this.i))};f.V=function(){return za(nd,this.u)};f.Z=function(a,b){return cc(this,b)};f.$=function(a,b,c){return dc(this,b,c)};
f.xa=function(a,b,c){a=fd(this.i,b);if(-1===a){if(this.l<Fe){a=this.i;for(var d=a.length,e=Array(d+2),g=0;;)if(g<d)e[g]=a[g],g+=1;else break;e[d]=b;e[d+1]=c;return new Wa(this.u,this.l+1,e,null)}return za(qa(Jc(qd,this),b,c),this.u)}if(c===this.i[a+1])return this;b=z(this.i);b[a+1]=c;return new Wa(this.u,this.l,b,null)};f.Ua=function(a,b){return-1!==fd(this.i,b)};f.I=function(){var a=this.i;return 0<=a.length-2?new id(a,0,null):null};
f.P=function(a,b){return b===this.u?this:new Wa(b,this.l,this.i,this.v)};f.T=function(a,b){if(Tb(b))return this.xa(null,U(b,0),U(b,1));a=this;for(b=I(b);;){if(null==b)return a;var c=J(b);if(Tb(c))a=qa(a,U(c,0),U(c,1)),b=N(b);else throw Error("conj on a map takes map entries or seqables of map entries");}};
f.call=function(a){switch(arguments.length-1){case 1:return this.g(arguments[1]);case 2:return this.h(arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",y.g(arguments.length-1)].join(""));}};f.apply=function(a,b){return this.call.apply(this,[this].concat(z(b)))};f.g=function(a){return this.ka(null,a)};f.h=function(a,b){return this.H(null,a,b)};var nd=new Wa(null,0,[],Be),Fe=8;Wa.prototype[ob]=function(){return O(this)};f=pd.prototype;
f.U=function(){if(this.Wa)return hc(this.Sa);throw Error("count after persistent!");};f.ka=function(a,b){return this.H(null,b,null)};f.H=function(a,b,c){if(this.Wa)return a=fd(this.i,b),-1===a?c:this.i[a+1];throw Error("lookup after persistent!");};
f.Za=function(a,b){if(this.Wa){if(hd(b))return this.Va(null,Vd.g?Vd.g(b):Vd.call(null,b),Yd.g?Yd.g(b):Yd.call(null,b));if(Tb(b))return this.Va(null,b.g?b.g(0):b.call(null,0),b.g?b.g(1):b.call(null,1));a=I(b);for(b=this;;){var c=J(a);if(u(c))a=N(a),b=Pa(b,Vd.g?Vd.g(c):Vd.call(null,c),Yd.g?Yd.g(c):Yd.call(null,c));else return b}}else throw Error("conj! after persistent!");};f.ib=function(){if(this.Wa)return this.Wa=!1,new Wa(null,hc(this.Sa),this.i,null);throw Error("persistent! called twice");};
f.Va=function(a,b,c){if(this.Wa){a=fd(this.i,b);if(-1===a){if(this.Sa+2<=2*Fe)return this.Sa+=2,this.i.push(b),this.i.push(c),this;a=rd.h?rd.h(this.Sa,this.i):rd.call(null,this.Sa,this.i);return Pa(a,b,c)}c!==this.i[a+1]&&(this.i[a+1]=c);return this}throw Error("assoc! after persistent!");};f.call=function(a){switch(arguments.length-1){case 1:return this.g(arguments[1]);case 2:return this.h(arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",y.g(arguments.length-1)].join(""));}};
f.apply=function(a,b){return this.call.apply(this,[this].concat(z(b)))};f.g=function(a){return this.H(null,a,null)};f.h=function(a,b){return this.H(null,a,b)};wd.prototype.advance=function(){for(var a=this.i.length;;)if(this.o<a){var b=this.i[this.o],c=this.i[this.o+1];null!=b?b=this.cb=new gd(b,c):null!=c?(b=Ua(c),b=b.ia()?this.pa=b:!1):b=!1;this.o+=2;if(b)return!0}else return!1};wd.prototype.ia=function(){var a=null!=this.cb;return a?a:(a=null!=this.pa)?a:this.advance()};
wd.prototype.next=function(){if(null!=this.cb){var a=this.cb;this.cb=null;return a}if(null!=this.pa)return a=this.pa.next(),this.pa.ia()||(this.pa=null),a;if(this.advance())return this.next();throw Error("No such element");};wd.prototype.remove=function(){return Error("Unsupported operation")};f=xd.prototype;f.Ra=function(a){if(a===this.D)return this;var b=ic(this.M),c=Array(0>b?4:2*(b+1));Vb(this.i,0,c,0,2*b);return new xd(a,this.M,c)};f.ab=function(){return Id?Id(this.i):Kd.call(null,this.i)};
f.bb=function(a,b){return vd(this.i,a,b)};f.za=function(a,b,c,d){var e=1<<(b>>>a&31);if(0===(this.M&e))return d;var g=ic(this.M&e-1);e=this.i[2*g];g=this.i[2*g+1];return null==e?g.za(a+5,b,c,d):kd(c,e)?g:d};
f.na=function(a,b,c,d,e,g){var h=1<<(c>>>b&31),k=ic(this.M&h-1);if(0===(this.M&h)){var l=ic(this.M);if(2*l<this.i.length){a=this.Ra(a);b=a.i;g.G=!0;c=2*(l-k);g=2*k+(c-1);for(l=2*(k+1)+(c-1);0!==c;)b[l]=b[g],--l,--c,--g;b[2*k]=d;b[2*k+1]=e;a.M|=h;return a}if(16<=l){k=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];k[c>>>b&31]=Gd.na(a,b+5,c,d,e,g);for(e=d=0;;)if(32>d)0===(this.M>>>d&1)?
d+=1:(k[d]=null!=this.i[e]?Gd.na(a,b+5,kb(this.i[e]),this.i[e],this.i[e+1],g):this.i[e+1],e+=2,d+=1);else break;return new zd(a,l+1,k)}b=Array(2*(l+4));Vb(this.i,0,b,0,2*k);b[2*k]=d;b[2*k+1]=e;Vb(this.i,2*k,b,2*(k+1),2*(l-k));g.G=!0;a=this.Ra(a);a.i=b;a.M|=h;return a}l=this.i[2*k];h=this.i[2*k+1];if(null==l)return l=h.na(a,b+5,c,d,e,g),l===h?this:ud(this,a,2*k+1,l);if(kd(d,l))return e===h?this:ud(this,a,2*k+1,e);g.G=!0;g=b+5;d=Ed?Ed(a,g,l,h,c,d,e):Fd.call(null,a,g,l,h,c,d,e);e=2*k;k=2*k+1;a=this.Ra(a);
a.i[e]=null;a.i[k]=d;return a};
f.ma=function(a,b,c,d,e){var g=1<<(b>>>a&31),h=ic(this.M&g-1);if(0===(this.M&g)){var k=ic(this.M);if(16<=k){h=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];h[b>>>a&31]=Gd.ma(a+5,b,c,d,e);for(d=c=0;;)if(32>c)0===(this.M>>>c&1)?c+=1:(h[c]=null!=this.i[d]?Gd.ma(a+5,kb(this.i[d]),this.i[d],this.i[d+1],e):this.i[d+1],d+=2,c+=1);else break;return new zd(null,k+1,h)}a=Array(2*(k+1));Vb(this.i,
0,a,0,2*h);a[2*h]=c;a[2*h+1]=d;Vb(this.i,2*h,a,2*(h+1),2*(k-h));e.G=!0;return new xd(null,this.M|g,a)}var l=this.i[2*h];g=this.i[2*h+1];if(null==l)return k=g.ma(a+5,b,c,d,e),k===g?this:new xd(null,this.M,td(this.i,2*h+1,k));if(kd(c,l))return d===g?this:new xd(null,this.M,td(this.i,2*h+1,d));e.G=!0;e=this.M;k=this.i;a+=5;a=Cd?Cd(a,l,g,b,c,d):Fd.call(null,a,l,g,b,c,d);c=2*h;h=2*h+1;d=z(k);d[c]=null;d[h]=a;return new xd(null,e,d)};f.sa=function(){return new wd(this.i)};var Gd=new xd(null,0,[]);
yd.prototype.ia=function(){for(var a=this.i.length;;){if(null!=this.pa&&this.pa.ia())return!0;if(this.o<a){var b=this.i[this.o];this.o+=1;null!=b&&(this.pa=Ua(b))}else return!1}};yd.prototype.next=function(){if(this.ia())return this.pa.next();throw Error("No such element");};yd.prototype.remove=function(){return Error("Unsupported operation")};f=zd.prototype;f.Ra=function(a){return a===this.D?this:new zd(a,this.l,z(this.i))};f.ab=function(){return Md?Md(this.i):Od.call(null,this.i)};
f.bb=function(a,b){for(var c=this.i.length,d=0;;)if(d<c){var e=this.i[d];if(null!=e){b=e.bb(a,b);if(wb(b))return b;d+=1}else d+=1}else return b};f.za=function(a,b,c,d){var e=this.i[b>>>a&31];return null!=e?e.za(a+5,b,c,d):d};f.na=function(a,b,c,d,e,g){var h=c>>>b&31,k=this.i[h];if(null==k)return a=ud(this,a,h,Gd.na(a,b+5,c,d,e,g)),a.l+=1,a;b=k.na(a,b+5,c,d,e,g);return b===k?this:ud(this,a,h,b)};
f.ma=function(a,b,c,d,e){var g=b>>>a&31,h=this.i[g];if(null==h)return new zd(null,this.l+1,td(this.i,g,Gd.ma(a+5,b,c,d,e)));a=h.ma(a+5,b,c,d,e);return a===h?this:new zd(null,this.l,td(this.i,g,a))};f.sa=function(){return new yd(this.i)};f=Bd.prototype;f.Ra=function(a){if(a===this.D)return this;var b=Array(2*(this.l+1));Vb(this.i,0,b,0,2*this.l);return new Bd(a,this.ya,this.l,b)};f.ab=function(){return Id?Id(this.i):Kd.call(null,this.i)};f.bb=function(a,b){return vd(this.i,a,b)};
f.za=function(a,b,c,d){a=Ad(this.i,this.l,c);return 0>a?d:kd(c,this.i[a])?this.i[a+1]:d};
f.na=function(a,b,c,d,e,g){if(c===this.ya){b=Ad(this.i,this.l,d);if(-1===b){if(this.i.length>2*this.l)return b=2*this.l,c=2*this.l+1,a=this.Ra(a),a.i[b]=d,a.i[c]=e,g.G=!0,a.l+=1,a;c=this.i.length;b=Array(c+2);Vb(this.i,0,b,0,c);b[c]=d;b[c+1]=e;g.G=!0;d=this.l+1;a===this.D?(this.i=b,this.l=d,a=this):a=new Bd(this.D,this.ya,d,b);return a}return this.i[b+1]===e?this:ud(this,a,b+1,e)}return(new xd(a,1<<(this.ya>>>b&31),[null,this,null,null])).na(a,b,c,d,e,g)};
f.ma=function(a,b,c,d,e){return b===this.ya?(a=Ad(this.i,this.l,c),-1===a?(a=2*this.l,b=Array(a+2),Vb(this.i,0,b,0,a),b[a]=c,b[a+1]=d,e.G=!0,new Bd(null,this.ya,this.l+1,b)):R.h(this.i[a+1],d)?this:new Bd(null,this.ya,this.l,td(this.i,a+1,d))):(new xd(null,1<<(this.ya>>>a&31),[null,this])).ma(a,b,c,d,e)};f.sa=function(){return new wd(this.i)};f=Hd.prototype;f.toString=function(){return bb(this)};
f.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return S(this,b,0);case 2:return S(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.g=function(b){return S(this,b,0)};a.h=function(b,c){return S(this,b,c)};return a}();
f.lastIndexOf=function(){function a(c){return T(this,c,Q(this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return T(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.g=a;b.h=function(c,d){return T(this,c,d)};return b}();f.O=function(){return this.u};f.X=function(){if(null==this.C){var a=this.qa,b=this.o+2;return Jd?Jd(a,b,null):Kd.call(null,a,b,null)}a=this.qa;b=this.o;var c=N(this.C);return Jd?Jd(a,b,c):Kd.call(null,a,b,c)};
f.N=function(){var a=this.v;return null!=a?a:this.v=a=tb(this)};f.J=function(a,b){return jc(this,b)};f.V=function(){return M};f.Z=function(a,b){return ac(b,this)};f.$=function(a,b,c){return bc(b,c,this)};f.aa=function(){return null==this.C?new gd(this.qa[this.o],this.qa[this.o+1]):J(this.C)};
f.fa=function(){var a=this,b=null==a.C?function(){var c=a.qa,d=a.o+2;return Jd?Jd(c,d,null):Kd.call(null,c,d,null)}():function(){var c=a.qa,d=a.o,e=N(a.C);return Jd?Jd(c,d,e):Kd.call(null,c,d,e)}();return null!=b?b:M};f.I=function(){return this};f.P=function(a,b){return b===this.u?this:new Hd(b,this.qa,this.o,this.C,this.v)};f.T=function(a,b){return V(b,this)};Hd.prototype[ob]=function(){return O(this)};f=Ld.prototype;f.toString=function(){return bb(this)};
f.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return S(this,b,0);case 2:return S(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.g=function(b){return S(this,b,0)};a.h=function(b,c){return S(this,b,c)};return a}();
f.lastIndexOf=function(){function a(c){return T(this,c,Q(this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return T(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.g=a;b.h=function(c,d){return T(this,c,d)};return b}();f.O=function(){return this.u};f.X=function(){var a=this.qa,b=this.o,c=N(this.C);return Nd?Nd(a,b,c):Od.call(null,a,b,c)};f.N=function(){var a=this.v;return null!=a?a:this.v=a=tb(this)};f.J=function(a,b){return jc(this,b)};
f.V=function(){return M};f.Z=function(a,b){return ac(b,this)};f.$=function(a,b,c){return bc(b,c,this)};f.aa=function(){return J(this.C)};f.fa=function(){var a=this.qa;var b=this.o,c=N(this.C);a=Nd?Nd(a,b,c):Od.call(null,a,b,c);return null!=a?a:M};f.I=function(){return this};f.P=function(a,b){return b===this.u?this:new Ld(b,this.qa,this.o,this.C,this.v)};f.T=function(a,b){return V(b,this)};Ld.prototype[ob]=function(){return O(this)};Pd.prototype.ia=function(){return!this.qb||this.xb.ia()};
Pd.prototype.next=function(){if(this.qb)return this.xb.next();this.qb=!0;return new gd(null,this.ca)};Pd.prototype.remove=function(){return Error("Unsupported operation")};f=Qd.prototype;f.toString=function(){return bb(this)};f.keys=function(){return O(Ud.g?Ud.g(this):Ud.call(null,this))};f.entries=function(){return new ed(I(I(this)))};f.values=function(){return O(Xd.g?Xd.g(this):Xd.call(null,this))};f.has=function(a){return Yb(this,a)};f.get=function(a,b){return this.H(null,a,b)};
f.forEach=function(a){for(var b=I(this),c=null,d=0,e=0;;)if(e<d){var g=c.ea(null,e),h=Ib(g,0,null);g=Ib(g,1,null);a.h?a.h(g,h):a.call(null,g,h);e+=1}else if(b=I(b))Ub(b)?(c=Ra(b),b=Sa(b),h=c,d=Q(c),c=h):(c=J(b),h=Ib(c,0,null),g=Ib(c,1,null),a.h?a.h(g,h):a.call(null,g,h),b=N(b),c=null,d=0),e=0;else return null};f.ka=function(a,b){return this.H(null,b,null)};f.H=function(a,b,c){return null==b?this.ha?this.ca:c:null==this.root?c:this.root.za(0,kb(b),b,c)};
f.gb=function(a,b,c){a=this.ha?b.m?b.m(c,null,this.ca):b.call(null,c,null,this.ca):c;wb(a)?b=wa(a):null!=this.root?(b=this.root.bb(b,a),b=wb(b)?xb.g?xb.g(b):xb.call(null,b):b):b=a;return b};f.sa=function(){var a=this.root?Ua(this.root):new Gc(nd);return this.ha?new Pd(this.ca,a):a};f.O=function(){return this.u};f.U=function(){return this.l};f.N=function(){var a=this.v;return null!=a?a:this.v=a=ub(this)};f.J=function(a,b){return dd(this,b)};f.Xa=function(){return new Rd(this.root,this.l,this.ha,this.ca)};
f.V=function(){return za(qd,this.u)};f.xa=function(a,b,c){if(null==b)return this.ha&&c===this.ca?this:new Qd(this.u,this.ha?this.l:this.l+1,this.root,!0,c,null);a=new sd;b=(null==this.root?Gd:this.root).ma(0,kb(b),b,c,a);return b===this.root?this:new Qd(this.u,a.G?this.l+1:this.l,b,this.ha,this.ca,null)};f.Ua=function(a,b){return null==b?this.ha:null==this.root?!1:this.root.za(0,kb(b),b,Xb)!==Xb};
f.I=function(){if(0<this.l){var a=null!=this.root?this.root.ab():null;return this.ha?V(new gd(null,this.ca),a):a}return null};f.P=function(a,b){return b===this.u?this:new Qd(b,this.l,this.root,this.ha,this.ca,this.v)};f.T=function(a,b){if(Tb(b))return this.xa(null,U(b,0),U(b,1));a=this;for(b=I(b);;){if(null==b)return a;var c=J(b);if(Tb(c))a=qa(a,U(c,0),U(c,1)),b=N(b);else throw Error("conj on a map takes map entries or seqables of map entries");}};
f.call=function(a){switch(arguments.length-1){case 1:return this.g(arguments[1]);case 2:return this.h(arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",y.g(arguments.length-1)].join(""));}};f.apply=function(a,b){return this.call.apply(this,[this].concat(z(b)))};f.g=function(a){return this.ka(null,a)};f.h=function(a,b){return this.H(null,a,b)};var qd=new Qd(null,0,null,!1,null,Be);Qd.prototype[ob]=function(){return O(this)};f=Rd.prototype;
f.U=function(){if(this.D)return this.count;throw Error("count after persistent!");};f.ka=function(a,b){return null==b?this.ha?this.ca:null:null==this.root?null:this.root.za(0,kb(b),b)};f.H=function(a,b,c){return null==b?this.ha?this.ca:c:null==this.root?c:this.root.za(0,kb(b),b,c)};
f.Za=function(a,b){a:if(this.D)if(hd(b))a=Sd(this,Vd.g?Vd.g(b):Vd.call(null,b),Yd.g?Yd.g(b):Yd.call(null,b));else if(Tb(b))a=Sd(this,b.g?b.g(0):b.call(null,0),b.g?b.g(1):b.call(null,1));else for(a=I(b),b=this;;){var c=J(a);if(u(c))a=N(a),b=Sd(b,Vd.g?Vd.g(c):Vd.call(null,c),Yd.g?Yd.g(c):Yd.call(null,c));else{a=b;break a}}else throw Error("conj! after persistent");return a};
f.ib=function(){if(this.D){this.D=null;var a=new Qd(null,this.count,this.root,this.ha,this.ca,null)}else throw Error("persistent! called twice");return a};f.Va=function(a,b,c){return Sd(this,b,c)};f.call=function(a){switch(arguments.length-1){case 1:return this.g(arguments[1]);case 2:return this.h(arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",y.g(arguments.length-1)].join(""));}};f.apply=function(a,b){return this.call.apply(this,[this].concat(z(b)))};
f.g=function(a){return this.ka(null,a)};f.h=function(a,b){return this.H(null,a,b)};f=Td.prototype;f.toString=function(){return bb(this)};f.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return S(this,b,0);case 2:return S(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.g=function(b){return S(this,b,0)};a.h=function(b,c){return S(this,b,c)};return a}();
f.lastIndexOf=function(){function a(c){return T(this,c,Q(this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return T(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.g=a;b.h=function(c,d){return T(this,c,d)};return b}();f.O=function(){return this.ra};f.X=function(){var a=(null!=this.B?this.B.j&128||G===this.B.Ya||(this.B.j?0:v(ma,this.B)):v(ma,this.B))?this.B.X():N(this.B);return null==a?null:new Td(a,null)};f.N=function(){return tb(this)};
f.J=function(a,b){return jc(this,b)};f.V=function(){return M};f.Z=function(a,b){return ac(b,this)};f.$=function(a,b,c){return bc(b,c,this)};f.aa=function(){return this.B.aa(null).key};f.fa=function(){var a=(null!=this.B?this.B.j&128||G===this.B.Ya||(this.B.j?0:v(ma,this.B)):v(ma,this.B))?this.B.X():N(this.B);return null!=a?new Td(a,null):M};f.I=function(){return this};f.P=function(a,b){return b===this.ra?this:new Td(this.B,b)};f.T=function(a,b){return V(b,this)};Td.prototype[ob]=function(){return O(this)};
f=Wd.prototype;f.toString=function(){return bb(this)};f.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return S(this,b,0);case 2:return S(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.g=function(b){return S(this,b,0)};a.h=function(b,c){return S(this,b,c)};return a}();
f.lastIndexOf=function(){function a(c){return T(this,c,Q(this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return T(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.g=a;b.h=function(c,d){return T(this,c,d)};return b}();f.O=function(){return this.ra};f.X=function(){var a=(null!=this.B?this.B.j&128||G===this.B.Ya||(this.B.j?0:v(ma,this.B)):v(ma,this.B))?this.B.X():N(this.B);return null==a?null:new Wd(a,null)};f.N=function(){return tb(this)};
f.J=function(a,b){return jc(this,b)};f.V=function(){return M};f.Z=function(a,b){return ac(b,this)};f.$=function(a,b,c){return bc(b,c,this)};f.aa=function(){return this.B.aa(null).G};f.fa=function(){var a=(null!=this.B?this.B.j&128||G===this.B.Ya||(this.B.j?0:v(ma,this.B)):v(ma,this.B))?this.B.X():N(this.B);return null!=a?new Wd(a,null):M};f.I=function(){return this};f.P=function(a,b){return b===this.ra?this:new Wd(this.B,b)};f.T=function(a,b){return V(b,this)};Wd.prototype[ob]=function(){return O(this)};
var de={'"':'\\"',"\\":"\\\\","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t"};H.prototype.Y=G;H.prototype.K=function(a,b,c){return be(b,Y,"("," ",")",c,this)};oc.prototype.Y=G;oc.prototype.K=function(a,b,c){return be(b,Y,"("," ",")",c,this)};gd.prototype.Y=G;gd.prototype.K=function(a,b,c){return be(b,Y,"["," ","]",c,this)};Hd.prototype.Y=G;Hd.prototype.K=function(a,b,c){return be(b,Y,"("," ",")",c,this)};id.prototype.Y=G;id.prototype.K=function(a,b,c){return be(b,Y,"("," ",")",c,this)};
sb.prototype.Y=G;sb.prototype.K=function(a,b,c){return be(b,Y,"("," ",")",c,this)};Tc.prototype.Y=G;Tc.prototype.K=function(a,b,c){return be(b,Y,"("," ",")",c,this)};mc.prototype.Y=G;mc.prototype.K=function(a,b,c){return be(b,Y,"("," ",")",c,this)};Qd.prototype.Y=G;Qd.prototype.K=function(a,b,c){return je(this,Y,b,c)};Ld.prototype.Y=G;Ld.prototype.K=function(a,b,c){return be(b,Y,"("," ",")",c,this)};sc.prototype.Y=G;sc.prototype.K=function(a,b,c){return be(b,Y,"("," ",")",c,this)};
Wd.prototype.Y=G;Wd.prototype.K=function(a,b,c){return be(b,Y,"("," ",")",c,this)};X.prototype.Y=G;X.prototype.K=function(a,b,c){return be(b,Y,"["," ","]",c,this)};lc.prototype.Y=G;lc.prototype.K=function(a,b){return E(b,"()")};Wa.prototype.Y=G;Wa.prototype.K=function(a,b,c){return je(this,Y,b,c)};Td.prototype.Y=G;Td.prototype.K=function(a,b,c){return be(b,Y,"("," ",")",c,this)};kc.prototype.Y=G;kc.prototype.K=function(a,b,c){return be(b,Y,"("," ",")",c,this)};var Za=new W(null,"meta","meta",1499536964),ab=new W(null,"print-length","print-length",1931866356),Xa=new W(null,"flush-on-newline","flush-on-newline",-151457939),$a=new W(null,"dup","dup",556298533),Ya=new W(null,"readably","readably",1129599760),ne=new W(null,"fallback-impl","fallback-impl",-1501286995),ae=new W(null,"more-marker","more-marker",-14717935),le=new W(null,"alt-impl","alt-impl",670969595);var Ge=BigInt(7);export const kotobaCapImports=ue;export const amuCompileImports=function(a,b,c,d,e){var g={};d=u(d)?d:{};a=e.W?e.W(a,b,c,d):e.call(null,a,b,c,d);g.kotoba=a;g["kotoba:cap"]=ue(b);return g};export const KOTOBA_CAP_MODULE="kotoba:cap";export const CLOCK_NOW_CAPABILITY_ID=Ge;